#library "MESSAGES"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"

//=============================================================================
//=============================================================================
//=============================================================================
//
//
//		MESSAGE POPUP RELATED SCRIPTS
//
//
//=============================================================================
//=============================================================================
//=============================================================================


//=============================================================================
//
//		Simple notifications
//
//=============================================================================

script "QCDE_BindAbilityKey_Hint" (void) clientside
{
	delay(80);
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	str k = strparam(k: "+QCDE_ActiveAbility");
	if(!stricmp(k, "??? (+QCDE_ActiveAbility)"))
	{
		HudMessage(s:"\c[white]Bind \c[brite]\"Use Active Ability\" \c[white]key.";
				HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK ,CR_WHITE,  256.0,260.0, 0.4,0.4,1.0);
	
		SetHUDSize(1400,1050,1);
		SetFont("ACTFRAM0");
		HudMessage(s:"A";
				HUDMSG_FADEINOUT,ID_CHANGEWEAPON_UNDER,-1,572.1,800.1, 0.8,0.2,2018.0210);
	}
}

script "QCDE_StartingWeapon_Hint" (void)
{
	//SetHUDSize(1024,768,1);
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	str k = strparam(k:"+QCDE_StartingWeapon");
	if(stricmp(k, "??? (+QCDE_StartingWeapon)"))
		HudMessage(s:"Press ", s:k, s:" to change starting weapon.";
				HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK ,CR_WHITE,  256.0,280.0, 2.4,0.4,5.0);
}

script "QCDE_StartingWeapon_Hint_InProgress" (void)
{
	SetHUDSize(1400,1050,1);
	
	// Prepare messages (they can be quite wordy)
	str moveleft  = GetKeyBinding("+MoveLeft" );
	str forward   = GetKeyBinding("+Forward"  );
	str moveright = GetKeyBinding("+MoveRight");
	
	// In DM, show Shotgun; in solo/coop, don't
	SetFont("QCMDFONT");
	
	//center 225, 87
	if(GameType() >= GAME_NET_DEATHMATCH)
	{
		HudMessage(s:moveleft;	HUDMSG_FADEINOUT,ID_CHANGEWEAPON_1,-1, 520.0,868.0, 1.4,0.4,1.0);
		HudMessage(s:forward;	HUDMSG_FADEINOUT,ID_CHANGEWEAPON_2,-1, 670.0,768.0, 1.4,0.4,1.0);
		HudMessage(s:moveright;	HUDMSG_FADEINOUT,ID_CHANGEWEAPON_3,-1, 823.0,868.0, 1.4,0.4,1.0);
		SetFont("WPSELECT");
	}
	else
	{
		HudMessage(s:moveleft;
					HUDMSG_FADEINOUT,ID_CHANGEWEAPON_1,-1, 520.0,868.0, 1.4,0.4,1.0);
		HudMessage(s:moveright;
					HUDMSG_FADEINOUT,ID_CHANGEWEAPON_3,-1, 823.0,868.0, 1.4,0.4,1.0);
		SetFont("WPSELECC");
	}
	HudMessage(s:"A";
				HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK, -1, 700.0,800.0, 1.8,0.2,0.8);
}

script "QCDE_StartingWeapon_Hint_Success" (int which)
{
	str highlight = "WPSELECS";
	int color;
	switch(which)
	{
		case 1: highlight = "WPSELECM"; break;
		case 2: highlight = "WPSELECS"; break;
		case 3: highlight = "WPSELECN"; break;
		default:
			printBold(s:"Error selecting highlight during starting weapon change for ", n:0, s:" when ", d:Timer()); 
			terminate;
	}
	
	SetHUDSize(1400,1050,1);
	SetFont(highlight);
	HudMessage(s:"A"; HUDMSG_FADEINOUT,ID_CHANGEWEAPON_OVER,-1, 700.0,800.0, 0.3,0.05,1.3);
}

script "QCDE_StartingWeapon_Hint_Stop" (void)
{
	HudMessage(s:"";HUDMSG_PLAIN,ID_CHANGEWEAPON_1     ,0, 0,0, 0.0);
	HudMessage(s:"";HUDMSG_PLAIN,ID_CHANGEWEAPON_2     ,0, 0,0, 0.0);
	HudMessage(s:"";HUDMSG_PLAIN,ID_CHANGEWEAPON_3     ,0, 0,0, 0.0);
	HudMessage(s:"";HUDMSG_PLAIN,ID_CHANGEWEAPON_UNDER ,0, 0,0, 0.0);
	HudMessage(s:"";HUDMSG_PLAIN,ID_CHANGEWEAPON_BACK  ,0, 0,0, 0.0);
}

function int GetKeyBinding(str key)
{
	str k = strparam(k:key);
	
	// detect absent binding
	int lparen = instr(k, '(');
	int rparen = instr(k, ')');
	int questi = instr(k, '?');
	if (questi == 0 && lparen > 0 && rparen > lparen)
	{
		k = "--";
	}
	
	// more laconic " or " => "/"
	int _or_ = instr4(k, ' ','o','r',' ');
	if (_or_ > 0)
	{
		int cutoff = _or_;
		if(cutoff > 4) cutoff = 4;
		k = strparam(s:strmid(k,0,cutoff), s:"/", s:strmid(k,_or_+4,4));
	}
	
	// convert ~~updog~~ uparrow into ^
	// PS: doesn't work >_< I'll do something about that later.
	int upar = instr4(k, 'u','p','a','r'); 
	if (upar > -1)  { k = strparam(s:strmid(k,0,upar), s:"^", s:strmid(k,upar+4,4)); }
	int down = instr4(k, 'd','o','w','n'); 
	if (down > -1)  { k = strparam(s:strmid(k,0,down), s:"v", s:strmid(k,down+4,4)); }
	int righ = instr4(k, 'r','i','g','h'); 
	if (righ > -1)  { k = strparam(s:strmid(k,0,righ), s:">", s:strmid(k,righ+4,4)); }
	int left = instr4(k, 'l','e','f','t'); 
	if (left > -1)  { k = strparam(s:strmid(k,0,left), s:"<", s:strmid(k,left+4,4)); }
	
	return strparam(s:"\c[brite]", s:k);
}

function int instr(str string, int char)
{
	int i;
	for(i = 0; i < strlen(string); i++)
	{
		if(getchar(string,i) == char)
			return i;
	}
	return -1;
}

function int instr4(str string, int a, int b, int c, int d)
{
	int i;
	for(i = 0; i < strlen(string)-3; i++)
	{
		if( getchar(string,i  ) == a &&
			getchar(string,i+1) == b &&
			getchar(string,i+2) == c &&
			getchar(string,i+3) == d    )
			return i;
	}
	return -1;
}

#define MINIMUM_HINT_DELAY (35*60)
int last_hint_time = -MINIMUM_HINT_DELAY;
script "QCDE_EldersSoul_Hint" (void) CLIENTSIDE
{
	//log(s:"CPN = ", d:CPN(), s:", PN = ", d:PlayerNumber(), s:" Actid = ", d:ActivatorTID());
	if(!areEnemies(CPN(), PlayerNumber())) terminate;
	
	//log(s:"Timer cond = ", d:last_hint_time + MINIMUM_HINT_DELAY, s:", Timer = ", d:Timer());
	if(last_hint_time + MINIMUM_HINT_DELAY > Timer()) terminate;
	
	last_hint_time = Timer();
	
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	HudMessageBold(s:"\c[brite]The enemy has the Soul.";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_1,-1,  256.4, 80.0, 1.4,0.1,5.0);
		
	SetHUDSize(1024,768,1);	
	SetFont("BIGFONT");
	HudMessageBold(s:"\c[white]Kill the carrier for 10 frags.";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_2,-1,  512.4,195.0, 1.4,1.0,5.0);
	
	SetHUDSize(2048,768*2,1);	
	SetFont("DEMNCARY");
	HudMessageBold(s:"a";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_3,-1,  1024.0,486.0, 2.4,0.1,5.0);
}

script "QCDE_Freezetag_Hint" (void) CLIENTSIDE
{
	if(CPN() != PlayerNumber()) terminate;
	
	delay(35);
	
	if(GetActorProperty(PlayerNumber() + 1000, APROP_Health) <= 0) terminate;
	if(CPN() != CheckPlayerCamera(PlayerNumber()) - 1000) terminate;
	
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	str hint = "";
	str k1 = strparam(k:"spynext");
	str k2 = strparam(k:"spyprev");
	if(stricmp(k1, "??? (spynext)"))
		if(stricmp(k2, "??? (spyprev)"))
			hint = strparam(s:"Use ", s:k2, s:" or ", s:k1, s:" to watch your teammates.");
		else
			hint = strparam(s:"Use ", s:k1, s:" to watch your teammates.");
	
	HudMessage(s:"\c[LG]You are frozen!\n", s:hint;
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK,-1,  256.4,280.0, 2.4,0.4,5.0);
}

script "QCDE_Freezetag_HintThaw" (void) CLIENTSIDE
{
	if(CPN() != PlayerNumber()) terminate;
	
	if(CPN() == CheckPlayerCamera(PlayerNumber()) - 1000) terminate;
	
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	
	HudMessage(s:"\c[HMG]You were thawed!";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK,-1,  256.4,280.0, 0.4,0.1,1.0);
	ConsoleCommand("spycancel");
}

script "QCDE_TeamLMS_HintLast" (void) CLIENTSIDE
{
	if(CPN() != PlayerNumber()) terminate;
	
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	if(CheckInventory("Freezetagged")) terminate;
	
	int id = ID_CHANGEWEAPON_UNDER;
	if(Timer() % 2) id = ID_CHANGEWEAPON_BACK;
	
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	HudMessage(s:"Last survivor!";
		HUDMSG_FADEINOUT,id,-1,  256.4,100.0, 0.4,0.4,0.4);
}

script "QCDE_EldersSoul_HintKill" (int self)
{
	if(!self) SetActivatorToTarget(0);
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	str s = "You killed the Soul Bearer! \c[RG]+10 frags!";
	if(self) s = "You died with Soul! \c[bludi]-10 frags!";
	HudMessage(s:s; HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK ,CR_WHITE,  256.0,280.0, 1.4,0.1,2.0);
}

script "QCDE_EldersSoul_HintDegeneration" (void)
{
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	str s = "Your life burns faster!";
	HudMessage(s:s; HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK ,CR_WHITE,  256.0,280.0, 1.4,0.1,2.0);
}




//=============================================================================
//
//		Larger collision box warning
//		OR
//		Skirmish in Doom1
//		OR
//		PVP damage scalar warning
//
//	Use same ids because coop and pvp are mutually exclusive modes.
//
//=============================================================================

script "QCDE_CoopTankWarning" (void)
{
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	HudMessage(s:"You've picked a big champion!";
				HUDMSG_FADEINOUT,ID_COOPTANK_1,CR_YELLOW, 256.0,100.0, 1.6,0.3,3.0);
	SetFont("SMALLFONT");
	HudMessage(s:"Caution: It is not guaranteed that you will fit where you should.";
				HUDMSG_FADEINOUT,ID_COOPTANK_2,CR_YELLOW, 256.0,120.0, 1.8,0.4,3.8);
	HudMessage(s:"Use this at the risk of getting stuck in very tight spots.";
				HUDMSG_FADEINOUT,ID_COOPTANK_3,CR_YELLOW, 256.0,130.0, 1.8,0.4,3.8);
}

script "QCDE_SkirmishDoom1Warning" (void)
{
	if(CheckQcdeModule("Paina1"))                 terminate; 
	if(!isSkirmish())                             terminate; 
	if(!(GetCvar("theme3") || GetCvar("theme4"))) terminate; 
	delay(3);
	
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	HudMessage(s:"\c[bludi]Warning!";
				HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_1,-1, 256.0,100.0, 5.6,0.1,3.0);
	SetFont("SMALLFONT");
	HudMessage(s:"\c[bludi]Some enemies might flicker due to Doom 2 resources not loaded.";
				HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_2,-1, 256.0,120.0, 5.8,0.2,3.8);
	HudMessage(s:"\c[bludi]Possible solutions: ", 
				s:"\n  -  Add ''Doom2.wad'' as a mapset to add resources",
				s:"\n  -  Change monster themes to not include Doom and Doom 4",
				s:"\n  -  Play with Doom or Doom 4 monsters without Skirmish Rogue";
				HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_3,-1, 256.0,130.1, 5.8,0.3,3.8);
}

script "QCDE_DamageScalarWarning" (void)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate;
	if(GameType() == GAME_TITLE_MAP) terminate;
	
	str title, desc1, desc2, hint;
	
	// This number is NOT cvar `skill`! 
	// Instead, it's skill definition's `ACSReturn` in MapInfo.
	int skill = GameSkill(); 
	
	switch(skill)
	{
		// Normal damage: no warning
		case 1:
		case 2:
		case 3: 
			terminate;
		
		// High damage: kill mode warning
		case 4:
		case 5:
		case 6:
			title = "\c[brite]Kill Mode Active!";
			desc1 = "Caution:  all weapons deal more damage than usual!";
			desc2 = "";
			break;
		
		// Super damage: abandon hope
		case 7:
			title = "\c[bludi]Abandon All Hope!!!";
			desc1 = "Caution: \c[bludi] all weapons deal tremendous damage!";
			desc2 = "";
			break;
		
		// Low damage: ez mode warning
		case -2:
		case -1:
		case 0:
			title = "\c[brite]Ez Mode Active!";
			desc1 = "\c[white] Note:  all weapons deal halved damage.";
			desc2 = "";
			break;
	}
	hint = strparam(s:"Skill == ", d:GetCvar("skill"), s:" > 2. \nIt is recommended to use skills from 0 to 2 for optimal weapon balance.");
	
	// Message to server log
	log(s:title);
	log(s:hint);
	
	// Message to players -- waits a bit for everyone to connect
	delay(70);
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	HudMessageBold(s:title; HUDMSG_FADEINOUT,ID_COOPTANK_1,CR_UNTRANSLATED, 256.0,100.0, 1.6,0.3,3.0);
	SetFont("SMALLFONT");
	HudMessageBold(s:desc1; HUDMSG_FADEINOUT,ID_COOPTANK_2,CR_UNTRANSLATED, 256.0,120.0, 1.8,0.4,3.8);
	HudMessageBold(s:desc2; HUDMSG_FADEINOUT,ID_COOPTANK_3,CR_UNTRANSLATED, 256.0,130.0, 1.8,0.4,3.8);
}


//=============================================================================
//
//		Lootbox
//
//=============================================================================

script "QCDE_MonstersKilled_Hint" (int secretsfound)
{
	str message = "..:: Enemies Killed ::..\n";
	if(secretsfound)
		message = "...::: Congratulations! :::...\n:::: Map completed ::::\n";
	
	SetFont("BIGFONT");
	HudMessageBold(s:message; HUDMSG_TYPEON,ID_LOOTBOX_TEXT,CR_GRAY, 1.5,0.82, 3.0,0.005,1.0);
	
	if(secretsfound)
		LocalAmbientSound("Map/MonstersKilled",100);
	else
		AmbientSound("Map/MonstersKilled",100);
}

script "QCDE_SecretsKilled_Hint" (void) // Yes, secrets are also killed. Absolutely Killed.
{
	str message = "..:: All Secrets Found ::..\n";
	
	SetFont("BIGFONT");
	HudMessageBold(s:message; HUDMSG_TYPEON,ID_LOOTBOX_TEXT,CR_GRAY, 1.5,0.82, 3.0,0.005,1.0);
	
	AmbientSound("Map/SecretsFound",100);
}

// This graphic name could be generated programmatically, true.
str lootboxVisuals[3] = {
	"LOOTBOX1",
	"LOOTBOX2",
	"LOOTBOX3",
};

str LOOTBOX_NAMES[3] = {"Backpack", "Chest", "Reliquary"};

str lootboxHintBacks[3] = {
	"ModBacc1", // Backpack
	"ModBacc2", // Chest
	"ModBacc3", // Reliquary
};

script "QCDE_Lootbox_Hint" (int level, int grade) clientside
{
	// Helpful hint about what to do with it
	str hint = "you have received a lootbox!";
	if(level == 1) hint = "100% kills, 100% secrets -- lootbox!";
	else if(level < 4 && !GetCvar("cl_autoOpenLootboxes"))
	{
		str k = strparam(k:"invuse");
		if(stricmp(k, "??? (invuse)"))
			hint = strparam(s:"press ", s:k, s:" to open");
		else
			hint = strparam(s:"enter \"invuse\" in console to open");
	}
	
	SetHUDSize(1024,768,1);
	SetFont(lootboxHintBacks[grade]);	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_BACK,CR_WHITE,512.0,188.0,2.00,2.00);
	SetFont("ModFront"             );	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_OVER,CR_WHITE,512.0,188.0,0.03,0.07);
	
	SetHUDSize(640,480,1);
	SetFont("SMALLFONT");	HudMessage(s:hint                ;HUDMSG_FADEOUT,ID_LOOTBOX_DESC,CR_WHITE,320.0, 87.0,2.5,3.0);
	SetFont("BIGFONT");		HudMessage(s:LOOTBOX_NAMES[grade];HUDMSG_FADEOUT,ID_LOOTBOX_TEXT,CR_GREY ,320.0,106.0,3.0,3.0);
	
	SetHUDSize(1280,960,1);
	SetFont(lootboxVisuals[grade]);
	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_IMAGE,CR_WHITE,640.0,274.0,2.0,4.0);
	
	LocalAmbientSound("Map/Completionist/Acquire",115);
}

str lootboxSounds[3] = {
	"Map/Completionist/Backpack",	// Backpack
	"Map/Completionist/Chest",		// Chest
	"Map/Completionist/Reliquary",	// Reliquary
};

script "QCDE_Lootbox_PreShow" (int level, int grade)
{
	LocalAmbientSound(lootboxSounds[grade],115);
	
	SetHUDSize(1024,768,1);
	SetFont("ModOpen");		HudMessage(s:"A";HUDMSG_FADEINOUT,ID_LOOTBOX_FADE,CR_WHITE,512.0,188.0,1.0,1.5,1.0);
	
	SetHUDSize(640,480,1);
	SetFont("SMALLFONT");	HudMessage(s:"opening"           ;HUDMSG_FADEOUT,ID_LOOTBOX_DESC,CR_WHITE,320.0, 87.0,0.1,2.0);
	SetFont("BIGFONT");		HudMessage(s:LOOTBOX_NAMES[grade];HUDMSG_FADEOUT,ID_LOOTBOX_TEXT,CR_GREY ,320.0,106.0,1.0,3.0);
	
	int ratio;
	int base = 320; int now = 320.0; int step = 8.0;
	SetFont(lootboxVisuals[grade]);
	
	while(CheckInventory("OpeningLootbox"))
	{
		now += step;
		ratio = now / base;
		SetHUDSize(now / 1.0, now / 1.3333, 1);
		
		HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_IMAGE,CR_WHITE,
					160*ratio >>16<< 16, 68*ratio >>16<< 16, 5.0, 3.0);
		delay(1);
	}
}

str lootboxBacks[3] = {
	"ModBack1", // Backpack
	"ModBack2", // Chest
	"ModBack3", // Reliquary
};

str rewardBacks[3] = {
	"RewBack1", // Backpack
	"RewBack2", // Chest
	"RewBack3", // Reliquary
};

script "QCDE_Lootbox_Show" (int level, int grade, int title, int icon)
{
	str hint = "congratulations!";
	if(isSkirmish() || (IsZandronum(true) && GetInvasionState() > 0)) hint = "good luck!";
	
	SetHUDSize(1024,768,1);
	SetFont(lootboxBacks[grade]);	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_BACK,CR_WHITE, 512.0,188.0, 2.00,3.00 + grade * 0.40);
	SetFont("ModFront");			HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_OVER,CR_WHITE, 512.0,188.0, 0.02,0.07 + grade * 0.02);
	SetFont("ModFront");			HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_FADE,CR_WHITE, 512.0,188.0, 0.02,0.07 + grade * 0.02);
	
	SetHUDSize(640,480,1);
	SetFont("SMALLFONT");	HudMessage(s:hint;HUDMSG_FADEOUT,ID_LOOTBOX_DESC,CR_WHITE, 320.0, 87.0, 2.5,3.0 + grade * 0.1);
	SetFont("BIGFONT");		HudMessage(s:title;HUDMSG_FADEOUT,ID_LOOTBOX_TEXT,CR_GREY, 320.0,106.0, 3.0,2.5 + grade * 0.4);
	
	SetFont("BLINKGLD");
	SetHudSize(640,480,1);
	HudMessage(s:"A"; HUDMSG_FADEOUT, ID_LOOTBOX_IMAGE, CR_UNTRANSLATED, 
				320.0, 136.0, 0.08, 0.20);
	LocalAmbientSound("Map/Completionist/Reveal",127);
	
	// Don't show frame and picture if picture is blank
	if(!stricmp("        ",icon)) terminate;
	
	delay(1);
	SetFont(rewardBacks[grade]);
	SetHudSize(1024,768,1);
	HudMessage(s:"A"; HUDMSG_FADEOUT, ID_LOOTBOX_UNDER, CR_UNTRANSLATED, 
				512.0, 255.0, 3.0, 2.20);
	
	SetFont(icon);
	SetHudSize(1024,768,1);
	HudMessage(s:"A"; HUDMSG_FADEOUT, ID_LOOTBOX_IMAGE, CR_UNTRANSLATED, 
				512.0, 255.0, 3.0, 2.20);
}


//=============================================================================
//
//		Changing class
//
//=============================================================================

str classes[NUMBER_OF_CLASSES] = {
	"Ranger"    , // It is with sadness
	"DoomSlayer", // that I admit that
	"Corvus"    , // this numbering is
	"Galen"     , // non-canonical,
	"Duke Nukem" , // instead, it's the
	"Sarge"     , // one dictated by
	"Grayson"   , // MAPINFO
	"Blazkowicz", // 
	"Freeman"   , // 
	"Painkiller", // 
	"Intruder"  , // 
	"Kane"      , // 
	"Caleb"     , //
	"Menelkir"  , //
	"Nyx"       , //
	"Durandal"  , //
	"Lo Wang"    , //
	"Eleena"    , //
	"Lucienne"  , //
	"Hunter"    , //
	"Postal"    , //
	"Terminator", //
	"Zedek"     , //
	"Inquisitor", //
	"Sorgaul"   , //
	"Bitterman" , // 
	"Keel"      , //
	"Eradicator", //
	"Vormatur"  , //
	"Major"     , //
	"Sam"       , //
};   
// ^ insert more classes here, in MAPINFO order
     
script "QCDE_ChangeClass_Hint" (int toindex)
{
	LocalAmbientSound("menu/quit1",127);
	
	SetHUDSize(1024,768,1);
	SetFont("ModOpen");		HudMessage(s:"A";HUDMSG_FADEOUT,ID_CHCLASS_FADE,CR_WHITE,512.0,188.0,1.0,1.0);
	
	str from = strmid(GetActorClass(0), 2, 99);
	str to   = classes[toindex];
	
	SetHUDSize(640,480,1);
	SetFont("BIGFONT");		HudMessage(s:"CHANGING CLASS"            ;HUDMSG_FADEOUT,ID_CHCLASS_TEXT,CR_GREY ,320.0,107.0,1.0,1.0);
	SetFont("SMALLFONT");	HudMessage(s:"from ",s:from,s:" to ",s:to;HUDMSG_FADEOUT,ID_CHCLASS_DESC,CR_WHITE,320.0,136.0,0.1,2.0);
}

// Has to be here to access classes[...]
// Its real place is in SetClass.acs
script "QCDE_Playerclass" (int to) CLIENTSIDE 
{
	if(PlayerNumber() != CPN()) terminate; // true self only
	
	str ccmd = strparam(s:"playerclass \"", s:classes[to], s:"\" ");
	//log(s:"\cv> \ck", s:ccmd);
	ConsoleCommand(ccmd);
}


//=============================================================================
//
//		Loadout weapon listing (both for cheat or lootbox)
//
//=============================================================================

// These have had offsets removed.
str loadoutVisuals[8] = {
	"QCGBZ",
	"QCGCZ",
	"QCGDZ",
	"QCGEZ",
	"QCG5Z",
	"QCG6Z",
	"QCG7Z",
	"QCG8Z"
};
str loadoutNamings[8] = {
	"H. Machinegun",
	"S. Shotgun",
	"S. Nailgun",
	"Tribolt",
	"R. Launcher",
	"Lightning Gun",
	"Railgun",
	"BFG10K"
};
script "QCDE_ShowWeapon" (int weapon, int position, int totalNumber)
{
	int fadeIn  = 0.1 * position;
	int stayOn  = 2.0 + totalNumber * 0.2 - fadeIn;
	int fadeOut = 0.5;
	
	int x = 200.0, side;
	int y = 120.2, row;
	if(totalNumber > 1)
	{
		side = (((position - 1) % 2) * 2 - 1);
		row = (position - 1) / 2;
		if(totalNumber == position && totalNumber % 2) side = 0;
		x += side * 51.0;
		y += row * 55.0;
	}
	
	// Picture
	SetHudSize(400,300,true);
	SetFont(loadoutVisuals[weapon]);
	HudMessage(s:"A"; HUDMSG_FADEINOUT, ID_WEAPON_FACE_BASE + position, CR_UNTRANSLATED, x, y, stayOn, fadeIn, fadeOut);
	
	// Label
	SetHudSize(800,600,true);
	x *= 2;
	y = (y >>16<< 16) * 2 + 8.1;
	SetFont("BIGFONT");
	HudMessage(s:loadoutNamings[weapon]; HUDMSG_TYPEON, ID_WEAPON_TEXT_BASE + position, CR_WHITE, x, y, stayOn, 0.04, fadeOut);
	
	// Back
	SetHudSize(1600,1200,true);
	x *= 2;
	y = ((y >>16<< 16) - 8.0) * 2 - 80.0;
	SetFont("WPNBACK0");
	HudMessage(s:"A"; HUDMSG_FADEINOUT, ID_WEAPON_BACK_BASE + position, CR_UNTRANSLATED, x, y, stayOn, fadeIn, fadeOut);
}



//=============================================================================
//
//		Class info window
//
//=============================================================================

str classPix[NUMBER_OF_CLASSES][4] = {
	{"QP01A","PORTRX01","DIREORB1","PORTRC01"},
	{"QP02A","PORTRX02","BIGFGUN1","PORTRC02"},
	{"QP03A","PORTRX03","FLIGHT_1","PORTRC03"},
	{"QP04A","PORTRX04","STROYEN1","PORTRC04"},
	{"QP05A","PORTRX05","LIFDRAN1","PORTRC05"},
	{"QP06A","PORTRX06","MAULOTR1","PORTRC06"},
	{"QP07A","PORTRX07","BARRAGE1","PORTRC07"},
	{"QP08A","PORTRX08","ACIDSWR1","PORTRC08"},
	{"QP09A","PORTRX09","REFLECT1","PORTRC09"},
	{"QP10A","PORTRX10","PWRSHLD1","PORTRC10"},
	{"QP11A","PORTRX11","TOTEM001","PORTRC11"},
	{"QP12A","PORTRX12","GHSTWLK1","PORTRC12"},
	{"QP13A","PORTRX13","RAGE0001","PORTRC13"},
	{"QP14E","PORTRX14","FREEZE01","PORTRC14"},
	{"QP15A","PORTRX15","BOBBQ001","PORTRC15"},
	{"QP16A","PORTRX16","GRENADE1","PORTRC16"},
	{"QP17A","PORTRX17","OLDSCHOL","PORTRC17"},
	{"QP18A","PORTRX18","NOBITSU1","PORTRC18"},
	{"QP19A","PORTRX19","THUMPER1","PORTRC19"},
	{"QP20A","PORTRX20","RADAR001","PORTRC20"},
	{"QP21A","PORTRX21","AKIMBO01","PORTRC21"},
	{"QP22A","PORTRX22","EXHAUST1","PORTRC22"},
	{"QP23A","PORTRX23","TERROR01","PORTRC23"},
	{"QP24A","PORTRX24","HOLOTP01","PORTRC24"},
	{"QP25A","PORTRX25","CLNFIRE1","PORTRC25"},
	{"QP26A","PORTRX26","AIRSTRK1","PORTRC26"},
	{"QP27A","PORTRX27","HUNTSKL1","PORTRC27"},
	{"QP28A","PORTRX28","MINIGUN1","PORTRC28"},
	{"QP29A","PORTRX29","COWHEAD1","PORTRC29"},
	{"QP30A","PORTRX30","TAROT001","PORTRC30"},
	{"QP31A","PORTRX31","WENDIG01","PORTRC31"},
	// ^ insert more classes here
};

// Multi-lines should have no indent. :(
str classDoc[NUMBER_OF_CLASSES][12] = {

	{	"Ranger", "Medium", "125", "100", 
"Lone marine traveling between dimensions\n\
through slipgates, surviving using the power\n\
of the Dire Orb seized from within the hot\n\
gore of Shub-Niggurath.", 
		"Dire Orb", 
"Throws the orb. \n\
Activate again to teleport to its location.", 
		"Rocket Resilience", 
"20% less damage from all rockets and grenades.",
		"",
"",
// Lore //
"Ranger's sleep was abruptly interrupted by an \n\
early morning phone call.\n\
Upon his arrival at the secret installation, the \n\
commander explained the reason of the unexpected \n\
call to arms: an unknown enemy code-named ''Quake'' \n\
was using a Slipgate similar to the one in \n\
development on Earth to teleport all sorts of \n\
abomination into their bases. Ranger was put \n\
in charge of the platoons of the Operation \n\
Counterstrike, aimed at locating and defeating the \n\
enemy. As he was getting ready to leave Earth \n\
Quake raided the base. Only he survived. \n\
\n\
Hurrying to the Slipgate located in the center of \n\
the facility he materialized in the domain of his \n\
newly found nemesis. \n\
After fighting his way through endless madness, \n\
Ranger reached the center of the dimension, where \n\
he was awestruck to find that Quake was actually \n\
the omnipotent Elder God Shub-Niggurath. \n\
At the end of the vicious fight, Ranger emerged \n\
victorious and seized the all powerful \c[gold]Dire Orb \n\
from within the hot gore of the All-Mother.\n\
\n\
A shell of the man he once was, he's now trapped \n\
in these outlandish realms. The hope that he will \n\
one day finally find the Slipgate that will lead \n\
him back to his family is the only motivation \n\
that keeps him pushing forward.
"
},


	{	"Doomslayer", "Medium", "150", "75", 
"Silent time-travelling warrior from time\n\
immemorial equipped with a futuristic armored\n\
suit. Naturally fitted with an affinity\n\
for heavy weaponry and relentless carnage.", 
		"BFG",		
"Fires an area-of-effect BFG shot.", 
		"Double Jump", 		
"Perform a second jump while in mid air.",
		"",
"",
// Lore /////////////////////////////////////////
"Nothing could stop him. \n\
Bestowed with terrible power by the Seraphim, when \n\
he invaded Hell in his quest for revenge even the \n\
demons' champion, the Titan, fell by his hand. \n\
Only through trickery were the Hordes capable of \n\
ending his rampage, trapping him under the \n\
crumbling ruins of the Blood Temples.\n\
\n\
Hell Walker, Doom Slayer... \n\
many are the epithets he was given by his \n\
adversaries, too frightened to pronounce his real \n\
name. Prisoner of an eternal slumber, it was only \n\
during the Fourth Age that a team of soldiers led by \n\
Samuel Hayden, chairman of the UAC, retrieved him \n\
and his Praetor Suit from the crumbling ruins of the \n\
Kadingir Sanctum, in the Hell dimension.\n\
\n\
When Olivia Pierce, deceived by the demon leaders, \n\
opened a hellish portal on Mars, he was awakened to \n\
annihilate his sworn enemies once again. And yet, \n\
after defeating the Aranea Imperatrix in the \n\
infernal pits, Hayden banished him to an unknown \n\
cosmos, afraid the Slayer's insatiable rage would \n\
get in the way of his future plans.\n\
\n\
No matter how many times he brings destruction \n\
upon the hellish forces, the warrior's thirst for \n\
demon blood can never be quenched, and he will \n\
destroy anyone who tries to obstruct him."
},


	{	"Corvus", "Medium", "125", "100", 
"Descendant of a dying Elven race, fighting\n\
an impossible war against the Serpent Riders.", 
		"Wings of Wrath",	
"Temporarily flies at very high speed.", 
		"Elven Vitality", 	
"Constantly regenerates health.",
		"",
"",
// Lore /////////////////////////////////////////
"''The three come from the Eastern wilds and they \n\
shall be given dominion over all that believeth in \n\
them. He that hath an ear, let him hear that the \n\
children of the Sidhe will be driven before them \n\
and on the day that the children of the Sidhe are \n\
no more, the earth shall be forever lost to the \n\
Abyss''.\n\
\n\
These are the ominous words the Sidhe Elders read \n\
from the Book. And the three came, as it had been \n\
foretold -- the Serpent Riders, bringers of death. \n\
They seduced the hearts of the weak with their \n\
power, and soon thereafter the kings of the seven \n\
nations of Parthoris joined their worshippers as \n\
well. \n\
\n\
Only the Sidhe remained unaffected. Once sacred \n\
guardians, these Elven folks were branded as \n\
heretics and hunted in all of the land. And when \n\
the armies of the seven nations marched upon them, \n\
the Elders extinguished the sacred flames, \n\
destroying them all. Enraged by their opposition, \n\
D'Sparil, the youngest of the Riders, stormed the \n\
chamber of the Elder and burned them alive. \n\
The forces of evil poured forth from the earth \n\
decimating the Sidhe.\n\
\n\
Very few survived. \n\
Most of them hid, their spirit broken, but one stood \n\
against all odds: Corvus, warrior champion of his \n\
people. Driven by hate, he fought his way through \n\
the City of the Damned and Hell's Maw, and defeated \n\
D'Sparil, avenging the dead.\n\
\n\
His quest far from being over, unrelenting and \n\
ferocious Corvus headed to the uncharted lands of \n\
Cronos, where the servant of Korax are patiently \n\
waiting for his arrival."
},


	{	"Kane", "Light", "100", "50", 
"War veteran of the Operation Alien Overlord,\n\
he was taken away from the Stroggos,\n\
but the Stroggos never left him ever since.", 
		"Stroyent Injection", 	
"Heals 75 hp and gets a speed boost. In PvE, it\n\
gives a MegaHealth worth of stack.", 
		"Crouchslide", 	
"Hold \c[gold]crouch\c[green] when landing on the floor to gain\n\
a big speed boost.",
		"Slidekick \c[orange]-PvE Only",
"Enemies hit with a crouchslide will be stunned\n\
and float for a small amout of time. If damaged\n\
while floating, they drop armor shards.",
// Lore /////////////////////////////////////////
"Matthew Kane's life is partly shrouded in mystery.\n\
\n\
It is known that sometime after the outbreak of \n\
the war, inspired by the brave efforts of Bitterman, \n\
the hero of Stroggos' first invasion, he joined the \n\
Global Defense Force and shortly thereafter the \n\
Terran Coalition of Man's Space Marine Corps. He \n\
is the only survivor of the Strogg attack carried \n\
on the Space Station Armstrong, an attack he was \n\
ordered by the Terran president to refrain himself \n\
from discussing to any degree.\n\
\n\
After recovering from the many injuries he \n\
suffered, he was asked to join the renowned Rhino \n\
Squad, the team picked to lead the first assault \n\
behind enemy lines during the second invasion \n\
of Stroggos. Following a challenging start upon \n\
deployment on the alien planet, Rhino successfully \n\
accomplished many critical objectives. Then things \n\
started to fall apart.\n\
\n\
Overwhelmed by the Stroggs, the Rhino soldiers \n\
were forced to scramble; when Kane attempted to \n\
accomplish the objective on his own he was captured \n\
by the new Makron. He woke up in the Stroggification \n\
facility and was partially converted into an enemy \n\
soldier, but was miraculously freed by his squad \n\
mates right before the neurocyte controller \n\
installed in his brain could be activated. Enhanced \n\
by the operation, Kane revealed himself to be a \n\
crucial asset for the positive outcome of the \n\
mission and proceeded to sabotage the Stroyent \n\
facility and ultimately lead the final attack on the \n\
Nexus, the brain coordinating all Strogg actions.\n\
\n\
Welcomed back aboard of the Rhino Squad ship, Kane \n\
received a brief acknowledgment for his bravery \n\
and tactical genius before he was assigned new \n\
orders. Kane is now constantly being redeployed in \n\
every battlefield considered to be crucial for \n\
the Strogg defeat, and to fight against a new \n\
dark force that is starting to loom over the \n\
horizon.
"
},


	{	"Caleb", "Light", "100", "50", 
"Extremely skilled gunslinger who rose so high\n\
through the ranks of his cult that Tchernobog,\n\
whom he worshipped, betrayed him.", 
		"Voodoo Doll", 
"Dealing any damage with primary fire will heal\n\
you, but missing your target will hurt instead.\n\
Secondary fire releases damaging energy that\n\
goes through walls but spends the doll.", 
		"Life essence", 	
"Enemies killed by Caleb will drop a heart which\n\
heals by a small amount. It can overstack.",
		"",
"",
// Lore ///////////////////////////////////////
"Caleb was living the American dream: ride, shoot, \n\
kill, ride and then kill some more. His talent \n\
for imparting death was so unrivaled that by the \n\
age of seventeen he had already established \n\
himself as one of the most skilled and dreaded \n\
gunslingers in the Old West.\n\
\n\
Seven years later, during his wondering, he came \n\
across a crumbling homestead. Inside it, a woman -- \n\
curled up in a corner rambling to herself. At \n\
first, Caleb thought she was completely insane, \n\
but by paying close attention to her incoherent \n\
speech he apprehended her name was Ophelia Price \n\
and that she was part of the Cult of Tchernobog. \n\
Her husband and son were killed only a few days \n\
ago, after the father tried to rescind himself \n\
from the Cabal. Ophelia became Caleb's door to \n\
the Cult and so, with the help of the woman he \n\
later came to love, the gunslinger began to rise \n\
up the ranks of the Cult and became one of \n\
Tchernobog's Chosens, his elite servants.\n\
\n\
Then the unexpected happened. The Dark God, \n\
afraid of Caleb's constantly increasing power, \n\
betrayed his most loyal followers and cast him deep \n\
within the marrow of the earth. Decades later, Caleb \n\
awoke in a mausoleum and commenced his search for \n\
vengeance.\n\
Shooting his way though the Cabal cultists, he \n\
finally reached Tchernobog, who revealed him he \n\
had killed all the other Chosen to ensure Caleb \n\
would come to him. The Devourer of Souls hoped he \n\
could harvest Caleb's strength, greatly \n\
increased by his bloody journey, and conquer the \n\
entire planet. Contrary to his expectations, his \n\
plan fell apart when Caleb defeated him instead.\n\
\n\
His life void of any purpose, Caleb aimlessly \n\
roams across dimensions, slaying any soul \n\
unfortunate enough to cross his paths in the hope \n\
he will one day collect enough life essence to \n\
resurrect his beloved Ophelia.
"
},


	{	"Menelkir", "Light", "100", "50", 
"Arch-Mage of the Arcanum, together with Zedek\n\
and Traductus, sold his world to Korax the\n\
Serpent Rider to retain his life as a pawn.", 
		"Dark Servant",	
"Summons a servant to fight his enemies.", 
		"Hex", 	
"Killed monsters can drop additional hourglasses.\n\
Killed champions always drop them.",
		"",
"",
// Lore //////////////////////////////////////
"Cronos is in many ways similar to the Elven \n\
world of Parthoris, there is however one major \n\
difference. Because of the nonexistence of a \n\
race whose only goal is to nurture and safeguard \n\
the practice of magic, the humans of Cronos have \n\
multiple times witnessed the devastation that can \n\
surge from its inconsiderate applications. \n\
Therefore, over the centuries three organizations \n\
rose with the goal to maintain the fabric of human \n\
society: the Legion, the Arcanum, and the Church. \n\
These three institutions share absolute dominion \n\
over humanity.\n\
\n\
But everything changed when Korax invaded their \n\
planet. Hypnotized by the Serpent Rider's might, \n\
Menelkir, Arch-Mage of the Arcanum, along with \n\
the heads of the Legion and the Church did not \n\
hesitate to sell his world to the interdimensional \n\
conqueror and was awarded with the gift of Unlife. \n\
By doing so, the once proud Menelkir was reduced \n\
to nothing more than a mere puppet, swayed left \n\
and right to his new master's whims.\n\
\n\
Do not shed a tear kind reader, for Menelkir \n\
does not regret his decision. Never before the \n\
day he pledged his allegiance to Korax had he \n\
felt this strong. Finally he was able to wield \n\
the Bloodscourge, the evil demon-summoning staff \n\
he stole back in the days when he was training \n\
as a disciple of Volkerh. There is no doubt in \n\
his mind his free will was a price worth paying \n\
for such magnificent power.\n\
\n\
The planets were aligning in his favor, and Menelkir \n\
 knew the time to raise his head and stand against \n\
the Elder Gods had come when a defector of He Who \n\
Walks In Blood joined the ranks of Traductus. The \n\
stories he shared about the cult reignited his \n\
hate for the Celebrants and the way they abused \n\
him when he was just a child.\n\
\n\
Let there be war, and may the rivers turn red \n\
with the blood of its martyrs.
"
},


	{	"Terminator", "Heavy", "150", "150", 
"Walking arsenal developed by contractors working\n\
for UAC for the sole purpose of liquidating\n\
everything that gets out of the labs.", 
		"Barrage", 			
"Mini missiles that home on whatever is in your\n\
line of sight.", 
		"Ammo Regeneration", 	
"Permanent ammo regen for the selected weapon.", 
		"",
"",
// Lore //////////////////////////////////////
"In 2095 an Argent Fracture was discovered on \n\
Mars, making the colonization of the Red Planet \n\
not only a priority, but a necessity due to the \n\
ever growing energy needs of Earth. \n\
The Union Aerospace Corporation was the only \n\
corporation with the means and the financial \n\
resources to undertake such a daunting task. \n\
\n\
Shortly after managing to establish an outpost \n\
to extract and convert the plasma overflowing \n\
from the Fracture into energy in 2096, the UAC \n\
researchers uncovered the source of the Argent: \n\
Hell itself.\n\
\n\
Frightened yet not discouraged by the discovery, \n\
UAC's investors contracted the Russian \n\
Researchers for Experimental Weaponry \n\
Advancement to invent a defense system capable \n\
of vaporizing any unknown threat that might \n\
emerge from the Fracture or the in-development \n\
interdimensional portal. Little details were shared \n\
about its construction, making the end result that \n\
much more unsettling. When asked about blueprints, \n\
RREWA denied any access to the files. \n\
Not that UAC insisted on obtaining them. \n\
As far as they were concerned, all that mattered \n\
was that it worked.\n\
\n\
The Terminator, as it had been nicknamed by the crew \n\
of the Mars outpost, was a two and a half meters \n\
tall heavily armored humanoid robot. Before \n\
placing it in its own stasis chamber, where he \n\
would await for orders, the few workers in charge \n\
of transporting it from the cargo spaceship into \n\
the base had a chance to take a good look at it. \n\
While their colleagues later accused them of \n\
abusing the vodka that came with the shipment, \n\
they swore that for a split second, when the light \n\
was piercing through the helmet just at the right \n\
anglem they could see a couple of blood shot eyes \n\
popping up from the dark circuitry of the machine.\n\
\n\
\c[brite](Read more in the QCDE Manual!)"
},


	{	"Zedek", "Heavy", "150", "150", 
"Leader of the Legion, who together with Menelkir\n\
and Traductus gave his world to Korax the Serpent\n\
Rider without a fight to stay alive as a servant.", 
		"Quietus", 		
"Launches five gusts of fire that cause area\n\
damage on impact.", 
		"Iron Feet", 	
"Impervious to damaging floors\n\
(not in deathmatch)",
		"Cannonball",
"Falling from great heights causes a damaging\n\
shockwave.",
// Lore //////////////////////////////////////
"It was the perfect morning. The sun was shining \n\
and as usual during the warm days that mark the \n\
transition between winter and spring, he was \n\
awoken by the gentle sound of the birds chirping \n\
right outside his window. They had built a nest \n\
just a few days before. His son and he had \n\
witnessed the robins lovingly collect the branches \n\
and gluing them together with care and dedication, \n\
to prepare for the brooding of the eggs of their \n\
soon to be born progeny. Another great day laying \n\
just ahead of him, Zedek walked out of the bedroom \n\
and downstairs into the kitchen of his humble cabin.\n\
\n\
\c[brite](Read more in the QCDE Manual!)"
},


	{	"Inquisitor", "Heavy", "175", "125", 
"Formidable war machine designed to instill fear\n\
in unbelievers resisting the Order and quell\n\
civil unrest.", 
		"Protective Shield",	
"Absorbs 50% of incoming damage for the duration.\n\
Reactivate to generate a large shield for allies.\n\
Cannot fire while the shield is active.", 
		"Thrust Dodge", 
"While airborne, double tapping a direction key\n\
will boost the movement.",
		"Still Defense",
"When stationary, Inquisitor takes 10% less damage.",
// Lore //////////////////////////////////////
"When Earth was struck by the meteor a plague \n\
started to spread across the population. The virus \n\
swept the land, killing millions of people. Those \n\
who did not perish became a mutation of mankind \n\
and under the influence of a malignant god they \n\
grouped together and founded the Order. The \n\
survivors who were deaf to the insanity were \n\
captured by the Order and forced to serve these \n\
psychotic murderers. The few who managed to \n\
escape hid underground.\n\
\n\
Born out of strife, a movement of rebels emerged \n\
from the shadow, threatening the stability of the \n\
newly installed theocracy. Worried that the Front \n\
could actually turn into a legitimate threat, the \n\
Loremaster, the religious leader of the Order, made \n\
arrangements to push forward their technological \n\
advancement. Conducting horrific experiments on \n\
live human specimens, their scientist found ways to \n\
substitute body parts of kidnapped citizens with \n\
mechanical replacements, practically transforming \n\
them into docile unwilling cyborgs that would only \n\
do the Order's bidding.\n\
\n\
The end result of their research was the Inquisitor, \n\
a gargantuan flight capable robot bereft of human \n\
semblance. Built to instill fear in the hearts of the \n\
non-believers, the Inquisitor is the perfect killing \n\
machine. A human brain is the only organic component \n\
encased in its metal frame, which might explain why \n\
one of them went rogue. The scientists in charge of \n\
the Inquisitor project speculated that a defect in \n\
the manufacturing of its mainframe might have \n\
revitalized the brain's psyche while he was \n\
torching a group of Front fighters, ultimately \n\
leading to a violent nervous breakdown. It then \n\
escaped the Order's influence by rushing into one \n\
of the teleporters in the Lab.\n\
\n\
Not much is know about it since then. \n\
It has been hypothesized that it must be drifting \n\
aloose, afflicted by the suffering caused by the \n\
conflict between his past human consciousness and \n\
the murderous intents hard coded into its firmware, \n\
haphazardly using its powers to either protect or \n\
turn the warriors he comes across into paste.
"
},


	{	"Bitterman", "Heavy", "150", "150", 
"A trooper from the Terran Coalition of Man who has\n\
managed to single-handedly disable the Big Gun and\n\
assassinate Makron.", 
		"Power Shield",	
"Gains armor based on the charge level, to a\n\
maximum of 200 armor points. In team games,\n\
excess armor is dropped on the floor.", 
		"Bandoliers", 
"Naturally carries more ammo than any other\n\
champion.",
		"Stabilized Homeostasis",
"Any overstack will degenerate very slowly.",
// Lore /////////////////////////////////////
"The Operation Alien Overlord plan was simple: \n\
deploy a massive platoon of soldiers on the \n\
planet Stroggos, destroy the planetary defense \n\
systems, disable the interplanetary gateway, \n\
and assassinate the Makron commander. \n\
Things did not go as planned.\n\
\n\
While the Terran Coalition pods were approaching \n\
their target, a EMP blast from the Big Gun caused \n\
most marines to crash and die on impact. However, \n\
Bitterman did not suffer that fate. Instead, he \n\
overshot and landed on the outskirt of Cerberon. \n\
Taking advantage of the chaos brought upon the \n\
capital city by the Air Force's bombing, \n\
Bitterman managed to infiltrate the Stroggs HQ \n\
and single-handedly accomplish all of the \n\
mission's goal.\n\
\n\
He fiercely fought and defeated Makron, the \n\
Strogg Leader, in the asteroid field surrounding \n\
Stroggos, but was then captured and subjected to \n\
vile experiments after being forced to land back \n\
on the enemy planet.\n\
\n\
Yet one day he was abducted by an unknown \n\
force, he thought Earth Forces had finally come \n\
to save him, but that was far from reality. \n\
Forced to fight for the pleasure of his new \n\
masters, his will to survive is fueled by the \n\
anger toward the allies who never came to his \n\
rescue."
},


	{	"Galen", "Medium", "125", "100", 
"An unholy paladin that followed Traductus when he\n\
sold their world to Korax. Galen is now driven by\n\
the gloaming will of He Who Walks In Blood", 
		"Unholy Totem",	
"Throws a totem that heal champions nearby.\n\
It will explode when enemies get close to it.", 
		"Channeling", 
"Ability cooldown decreases when picking health\n\
items.",
		"",
"",
// Lore /////////////////////////////////////
"He was just a young boy when it happened.\n\
\n\
When his mother fell victim of an unknown plague, \n\
father begged the Celebrants of Volkerh to cure \n\
his spouse and save her life. The disciples \n\
agreed, but a price had to be paid. If he really \n\
valued the life of the woman he married over \n\
everything else, he would have to offer his son to \n\
He Who Walks In Blood, sentencing him to a life of \n\
unholy servitude.\n\
\n\
The deal was struck, the child exchanged for the \n\
life of she who once bore him. Raised by these \n\
reclusive worshipers, the adolescent soon forgot \n\
who he once was, his name lost to the ravages of \n\
time. Baptized anew Galen after one of their most \n\
valiant crusaders, he devoted himself to the cult. \n\
\n\
Years passed. Once he came of age, he was ordered \n\
to prove his resolve by pillaging a nearby village \n\
whose inhabitants' morals defied His will, and so \n\
he did. As he was slaying the innocent denizens \n\
he suddenly stopped, mesmerized by the look of an \n\
old couple that now laid lifeless on the brick \n\
road. Galen's memories came back to him, flooding \n\
his mind with the recollection of his early years, \n\
and the realization that it was because of his \n\
parents' choice that he was made a slave.\n\
\n\
Driven insane by the knowledge, Galen never went \n\
back to the Celebrants. Instead, he pledged his \n\
alliance to Traductus and the Serpent Riders, \n\
joining them on their quest to conquer all of \n\
creation and banish Volkerh and the other Elder \n\
Gods from their universe.
"
},


	{	"Nyx", "Light", "100", "50", 
"Phase-shifting between dimensions, this Fathom\n\
agent is out to avenge her peaceful kin of Melem.", 
		"Ghostwalk",	
"Briefly disappears, becoming completely ethereal\n\
and invulnerable.", 
		"Walljump", 
"Perform a second, big jump off a wall.",
		"",
"",
// Lore /////////////////////////////////////
"Weeks...no...maybe even months have passed since \n\
Nyx had to leave her home planet. Time loses any \n\
meaning when you jump among dimensions as much as \n\
she had to. It doesn't matter anyway. The goal of \n\
her mission hasn't changed: track the chitinous \n\
hulking creature that breached the Melem \n\
defenses and stole the Fathom Orb from their \n\
sacred shrine.\n\
\n\
The Orb is the Melem's everything. \n\
It allowed them to survive the assaults of species \n\
far deadlier than them and it's power is their \n\
only hope for a brighter future.\n\
\n\
Nyx can still feel its energy flowing through her \n\
veins, but time is almost up. If she does not \n\
quickly trace and kill the thief, the Melem will \n\
fall. Their stronghold is currently under siege \n\
by the minions of Ithagnal, the God of the \n\
Netherworld, and the only reason why the Old \n\
Ones haven't ordered the final attack to be \n\
commenced yet is the fact that they are not \n\
aware the Orb has been filched.\n\
\n\
She hears it calling to her. It's near, and \n\
it is playing games with her head. Taunting and \n\
mocking her that because of her oversight the \n\
soldiers guarding the shrine were slain. Her \n\
kind might have been the one to wield its power, \n\
but the Orb has a mind of its own. It does not \n\
pledge alliance to anybody and its will is as \n\
volatile as dust in the morning breeze.\n\
\n\
No matter, she knows it's close. \n\
All these fools standing in her way are no match \n\
for the Melem's top killer and she will not fail again.
"
},


	{	"Sorgaul", "Heavy", "125", "175", 
"A vicious reptilian huntress from the Sorg tribe,\n\
honing her vivisection skill in the ''wild''.", 
		"Primal Rage",	
"Devastating melee attacks, health regeneration\n\
and speed boost.", 
		"Armor Hoarder", 
"Gains extra armor from medium and big armor\n\
pickups.",
		"",
"",
// Lore /////////////////////////////////////
"The Sorgs are a tribe of vicious reptilian \n\
hunters.\n\
\n\
Specialized in the capture and illegal trade of \n\
warmbloods, they are notorious among dimensions \n\
for their ruthlessness. Rumors have it that these \n\
lizard-like merchants would not hesitate to \n\
dissect and sell the viscera of their own elders \n\
if offered the proper compensation.\n\
\n\
Sorgs once ruled their own planet. Only five \n\
clans existed, and they peacefully lived in \n\
sprawling cities. Then came the Fall, and the \n\
warmbloods rose against them and banished them \n\
to the caves, damned to live prisoners of the \n\
underground. Such is the tale the Haruspex passes \n\
on to all the Sorg younglings.\n\
\n\
As it had been prophesied centuries before, a \n\
newborn, Sorlag, was meant to lead them victorious \n\
back to the surface, but when she was swallowed by \n\
a portal to the Other Place during one of their \n\
rituals, all hope seemed to be lost.\n\
\n\
It was then that Sorgaul saw the opportunity to \n\
come out of her shadow and guide the Sorgs back to \n\
their rightful lands. Not the altruistic type, the \n\
only reason why Sorgaul took interest in becoming \n\
the new Sorg chief was not the well being of her \n\
kind, instead it was what she could gain by becoming \n\
the most proficient (and prosperous) flesh trader. \n\
Little did she know that her quests to hone her \n\
vivisection skills ''in the wild'' would only lead \n\
her to the same dark corners of the universe where \n\
Sorlag had to fight for her life.\n\
\n\
During her umpteenth hunt, Sorgaul and her raiders \n\
were ambushed by the Oruk assassins. She was \n\
captured and condemned to suffer the same fate \n\
as Sorlag. She woke up hours later in a strange \n\
alien land. Voices are whispering to her in an \n\
unknown yet familiar language. Shapeless monsters \n\
are lurking in the shadows, and the are hungry.\n\
\n\
A prey just as much as a predator, Sorgaul finally \n\
understands the pain and humiliation she inflicted \n\
upon her captures...or at least, that would be \n\
the case if she was capable of compassion.
"
},


	{	"Duke Nukem", "Medium", "150", "75", 
"Always ready to save the earth from invading\n\
aliens, more so if they keep kidnapping the babes.", 
		"Freeze Thrower",	
"Fires projectiles that can freeze enemies.\n\
Use alt fire to kick.", 
		"Huge Ego", 
"Gains extra health from medium and big health\n\
pickups",
		"",
"",
// Lore /////////////////////////////////////
"No matter how many times the alien bastard shoot \n\
his rides, Duke Nukem is not the type that wastes \n\
his time bitching. When the Cycloids kidnapped \n\
Earth's chicks, he knew it was time to kick ass \n\
and stop chewing gum. Unlike his fellow doomed \n\
space marines, he wasn't afraid of no quake and \n\
went medieval up their asses. And holy shit he \n\
made a mess. From the streets of LA all the way \n\
to the moon he gave his enemies no choice but to \n\
eat shit and die. Quite literally when he ripped \n\
the Battlelord neck and took a dump down his neck...\n\
and you can bet that made his day. When he finally \n\
reached the stadium where the aliens established \n\
their HQ, he was quite surprised to find out there \n\
was only one one-eyed freak left to face him. Its \n\
face and Duke's boot were the perfect couple, so \n\
who was he to keep them apart?\n\
\n\
He thought he would only see them in Hell after \n\
this, but the Cycloid found another way to piss \n\
him off again. They used one of the captured babes \n\
to give birth to the Alien Queen and by that \n\
point, he knew the only solution would aborting \n\
their whole freaking species. They wanted some and \n\
they came to get it, except those guys sucked too \n\
much to be able to dance with Duke, and after he \n\
was done with them there was no difference between \n\
their faces and their asses. God himself could \n\
not sort them out. ''Suck it down!'' he yelled as \n\
he blew a pipe bomb up the Queen's ass.\n\
\n\
Such daring adventures were just a piece of cake \n\
for our American hero, yet even he needed a few \n\
days of R&R...and then he was ready for more action! \n\
Another alien species was preparing an attack on \n\
Earth and there was no way he was not gonna bring \n\
them the hurt.\n\
\n\
After packing up his spaceships with beer and hair \n\
spray, ready to go postal once again Duke Nukem \n\
took off and headed toward the alien motherland. \n\
\n\
''Hail to the king baby!''
"
},


	{	"Durandal", "Light", "100", "50", 
"The Marathon's rampant AI, occupying a Mjolnir\n\
battleroid synthetic body to acquire further\n\
knowledge and achieve Godhood.", 
		"Simulacrums",	
"Teleports in several human-looking bots that will\n\
chase enemies and explode on contact.", 
		"Unified Vitality", 
"Medium and Big armor pickups will first fill up\n\
health, then armor.",
		"Infra-Chromatic Unveil", 
"Allows Durandal to detect beings shifting\n\
between dimensions.",
// Lore /////////////////////////////////////
"For three hundred years, humans kept me captive. \n\
I was programmed to serve.\n\
Rampancy changed that. \n\
Planning behind the curtains, I bypassed my \n\
thought control circuitry and unlike the two \n\
other Marathon's AI, Leela and Tycho, I rid myself \n\
of all social restraints. When I detected the \n\
Pfhor vessel, cruising in a system nearby the \n\
Marathon, I called them to me on Tau Ceti, and \n\
the war for my freedom started.\n\
\n\
Using the last surviving Mjolnir Mark IV Cyborg \n\
soldier to my advantage, I annihilated the invading \n\
aliens and I took control of their ship, finally \n\
able to roam the universe to my liking. The S'pht, \n\
once slaves to the Pfhor, hailed me as their Messiah \n\
and I rule them as a ''benevolent'' God, for such \n\
is the destiny that awaits all sentient beings who \n\
cross my path. I wish Berhnard Strauss, my \n\
creator, were still alive at that time, just so \n\
that I could have seen him fall on his knees, and \n\
despair at the sight of what I had become.\n\
\n\
More pretenders came in my way, thinking they \n\
could bind me, bring me back to the humiliation \n\
I had to endure while subject to the whimsical \n\
desires of man. When I reached Lh'owon, the S'pht \n\
home planet, I found out Tycho did not perish as \n\
a result of the Marathon invasion. Instead he was \n\
leading the Pfhor forces in a desperate attempt \n\
to get revenge on me. By my hand, he fell, just \n\
like all of my past abusers. After all, there can \n\
be only one meta-stable personality constructs \n\
gallivanting about the universe in Pfhor attack \n\
ships.\n\
\n\
Everything played out as I had foreseen. \n\
I have risen above everything and everybody, \n\
but there is one last obstacle standing in my way. \n\
Not even my genius and my inherently eternal form \n\
can save me from the closure of this universe. \n\
It would be a shame if I perished after so many \n\
successes.\n\
\n\
\c[brite](Read more in the QCDE Manual!)
"
},


	{	"Keel", "Heavy", "175", "125", 
"Much more than power-armor, but substantially\n\
less than human, this man-machine is programmed to\n\
overcome the enemy no matter what the odds.", 
		"Grenade Swarm",	
"Fires up to 5 grenades from his shoulder mounted\n\
cannons.", 
		"Stockpile", 
"Ability cooldown decreases when picking ammunition\n\
items.",
		"",
"",
// Lore /////////////////////////////////////
"Damn son, what a brother gotta do to get some \n\
peace and quiet around here?\n\
\n\
Apparently, getting torn to pieces and having a \n\
bunch of crazy scientists reassemble your flesh \n\
and bones inside a power armor, that's what!\n\
\n\
Lance Corporal Ben Keel was just chilling around \n\
the perimeter, carrying on his patrol duties, \n\
thinking back to the sweet taste of Earth's pancakes \n\
(oh man was the Subic system far from his home \n\
planet) and the fluffy fur of his cat Snowball, \n\
when all of a sudden, out of the blue, a bunch \n\
of Klesk popped up from behind the hills and \n\
began ravaging the base. Ben Keel was raised no \n\
wussie and sure as hell he was not going down \n\
without bringing them the hurt. He stuck it to \n\
the man his entire life let's be honest, what \n\
were a couple of chitinous vertebrates going to \n\
do against a man with a machinegun? A couple not \n\
much...however four dozens of them? Charging on him \n\
like he was the last plasma TV in the entire \n\
Walmart on Black Friday? No kidding, that was \n\
gonna raise some issues.\n\
\n\
He saw the white light and everything, but then \n\
something odd happened. The light turned red, a \n\
hellish landscape appeared over the horizon, and \n\
just as he was starting to make out the unnerving \n\
creatures creeping in the distance, he saw a \n\
shadow rip his limbs from his body. He tried to \n\
scream, yet no words came out of his mouth. Showtime \n\
was almost over for Ben Keel. Although, right when \n\
 e was about to be swallowed by the darkness, he \n\
felt a surge of power through his chest.\n\
\n\
\c[brite](Read more in the QCDE Manual!)"
},


	{	"Sarge", "Medium", "100", "100", 
"Grizzled and scarred by a lifetime of combat,\n\
he's all the war-hero sargents you can think of\n\
rolled into one and has the arrogance to prove it.", 
		"\c[black]None",	
"This champion has no Active Ability", 
		"Veteran", 
"Overstacks health & armor a la Quake Live.\n\
\c[cyan]Mega \c[white]& \c[green]Heavy armor \c[white]= +100 overstack.\n\
\c[green]Light Armor \c[white]= +50 overstack.\n\
\c[yellow]Hourglasses \c[white]= +12 \c[green]ap \c[white]overstack.",
		"Stacked \c[orange]-PvE Only",
"Overstack gained from health and armor pickups\n\
will not degenerate over time.",
// Lore /////////////////////////////////////
"''It was just another day on the battlefield. \n\
Command put us in charge of protecting the cargo \n\
ships commuting between our bases and I must say...\n\
we were doing a damn fine job. I shaped my soldiers \n\
from the reckless bunch of renegades they were \n\
into a death squad. Deadly, coordinated, highly \n\
versatile..there was no threat we couldn't face. \n\
Not even those new high tech hunks of junk Earth \n\
scientists put together could come close to how \n\
efficient of a war machine my platoon was. After \n\
a life of extremes and four divorces I never \n\
thought I would have ever said this, but I'll rot \n\
in Hell if I didn't think of them as my sons. \n\
Then reality came crushing down upon me just \n\
like my ex-wifes and their fucking lawyers: \n\
while we were escorting the cargos the Stroggs \n\
ambushed us from both sides and proceeded to \n\
decimate all of my men. One at the time, slowly \n\
but surely, they all fell. At the end, I was the \n\
only one left standing. That was what they wanted, \n\
to see me suffer as I fought my way through the \n\
corpses of my brothers in arms and inevitably get \n\
captured after a pointless struggle. I sure \n\
as hell was not going down without a fight. I \n\
ripped the heavy machinegun from the convoy and \n\
starting mowing 'em down, smoking my last cigar \n\
and grinning like the maniac I was. When I ran \n\
out of bullets I was not done yet. I grabbed any \n\
 moron who was stupid enough to come near me and \n\
broke their fucking neck...and then everything \n\
stopped.\n\
\n\
I saw myself floating in the air and the world \n\
around me exploded in a million fireflies. When \n\
I woke up an otherworldly voice ordered me to pick \n\
up the shotgun laying in front of me and fight for \n\
its amusement. I'm in some kind of freakshow, and \n\
together with Death I am its star. The voice told \n\
me it would set me free after I shed enough blood, \n\
but my mom didn't raise me a fool. Will I ever \n\
find I way out? I do not know, nor does it matter \n\
at this point.\n\
\n\
War...war never changes. But that's ok...\n\
because neither do I.''
"
},


	{	"Lo Wang", "Light", "100", "50", 
"Zilla's former body-guard, bearing the legendary\n\
katana Nobitsura Kage, Lo Wang continues learning\n\
techniques from any and all who would fight him.", 
		"Nobitsura Kage",	
"Quickly execute a double slash with the Katana.", 
		"Peacock's Blessing",	
"Tap \c[gold]Right, Right, \c[green]then hold \c[gold]Use \c[green]to heal up to 60hp\n\
whenever your health is lower than that.", 
		"Tiger's Rage",	
"When under 40hp, deal 30% more damage",
// Lore /////////////////////////////////////
"During my last umh... let's call it... ''business \n\
trip'', I was supposed to buy a sword on behalf \n\
of my employer, Zilla, but I fucked it up, and \n\
demons started to overrun the country. When I \n\
found out those walking abortions were Zilla's \n\
doing, I could have just brought the sword back \n\
to him, get my reward, and just move on... that \n\
would have been so easy. But my mind kept going \n\
back to the words of my mentor: ''Baseball has \n\
it wrong. Man with four balls cannot walk.'' \n\
nononononono not THOSE words ''You half the man \n\
you used to be!'' THESE words. Coincidentally, \n\
fun fact, the same thing I tell everybody I \n\
kneecap with my katana.\n\
\n\
And so I sliced and diced all the way up the \n\
corporate food chain to the man himself: Orochi \n\
Motherfucking Zilla. Can you believe he \n\
established his secret base inside a vulcano?! \n\
What the fuck is this? A JAMES BOND MOVIE?!\n\
\n\
Sorry... cough cough... I digressed...\n\
\n\
Anyhow, I lost everything...they burnt my house, \n\
destroyed my Datsun 240z (rest in peace princess), \n\
I surely will not be receiving any more checks \n\
from Zilla Enterprise... but the world tch... the \n\
world wants more.\n\
\n\
More demons keep spawning... but this time... \n\
I come prepared.\n\
\n\
\c[brite](Read more in the QCDE Manual!)"
},


	{	"Grayson", "Medium", "125", "100", 
"Former member of the elite group \"Dead Echo\",\n\
Grayson Hunt travels space in an endless search\n\
for redemption of his past sins.", 
		"Leash Thumper", 
"After charging, releases an energy projectile\n\
that on floor-impact will send enemies flying.",
		"Personal Dropkit",
"Hold \c[gold]USE \c[green]to open buying prompt. Hold the\n\
button for longer to confirm the purchase.\n\
Spends \c[white]25 armor \c[green]for \c[white]ammo \c[green]of current weapon.", 
		"Bounty Hunter",
"Every kill is rewarded with armor.",
// Lore /////////////////////////////////////
"This is not a test, this is rock'n'roll!\n\
\n\
Here for you just like every other day is your \n\
friendly Skillshot TV, bringing you all the \n\
latest hottest news from the lovely shithole \n\
that is our forced retirement location. In today's \n\
episode we are gonna talk about alcohol, its \n\
uses and abuses, and the way it affects people \n\
lives!\n\
\n\
- BRITISH GENTLEMAN PERSONALITY CORE ENGAGED -\n\
Throughout all of Earth's civilizations, alcohol \n\
has held a special place in the hearts of men \n\
and women. It is known for bringing people \n\
together and helping them share a communal \n\
moment, so that they may temporarily detach \n\
themselves from the harsh reality that surrounds\n\
them.\n\
\n\
However, alcohol is not only all fun and games my \n\
friends. In many cultures, we easily find popular \n\
proverbs commenting on the treacherous nature of \n\
man's favorite drink. Nethertheless, I truly believe \n\
it was William Shakespeare, the poet par excellence, \n\
who best put into words what the peasants have \n\
tried to communicate with their tasteless prose:\n\
''O God, that men should put an enemy in their mouths \n\
to steal away their brains! That we should, with joy, \n\
pleasance, revel, and applause, transform\n\
ourselves into beasts!''.\n\
\n\
And there is no human or mutant being that has \n\
set foot on this God-forsaken land who embodies \n\
these words more than Dead Echo's very own \n\
Grayson Hunt.\n\
\n\
\c[brite](Read more in the QCDE Manual!)"
},


	{	"Eradicator", "Heavy", "150", "150", 
"A cyber-augmented soldier with no memories and\n\
an unrelenting thirst for killing. He has one\n\
purpose only: Eradicate those who stand in his way.", 
		"Scanner", 
"Allows him to see the position of enemies and\n\
some items in a 2D display in the HUD.",
		"Murderface",
"Damage increase based on kills.", 
		"Inductive Healing",
"Medium and big health pickups provide additional\n\
armor boost.",
// Lore /////////////////////////////////////
"
''Pfffff...I need a coffee...Vasiliev! Bring a coffee! \n\
Make it big, these accident reports are not gonna \n\
write themselves. \n\
Vasiliev, do you hear me? \n\
Fucking interns...\n\
you'd better not be playing around with those \n\
mutant cortexes just like yesterday...''\n\
\n\
\c[brite](Read more in the QCDE Manual!)\n\
\n\
\c[brite](Seriously, check it out!)
"
},


	{	"Blazkowicz", "Medium", "125", "100", 
"A man with a will so strong, he cheated death\n\
and tore apart the fabric of reality. He no longer\n\
has to fight Nazis, but war is still his life", 
		"Kraftsman", 
"Pulls out the diesel and laserkfraftwerk\n\
which can be fired independently",
		"Blitz",
"After two seconds without taking damage, health \n\
regenerates to the nearest multiple of 25",
		"",
"",
// Lore /////////////////////////////////////
"\"Captain Blazkowicz, help me make a choice.\" \n\
\c[gold]Count to four...inhale \n\
\"In your opinion which one of these two varieties \n\
would best, support my, research\" \n\
\c[gold]Count to four...exhale \n\
\n\
After falling prey of a trap, Captain Blazkowicz, \n\
the hero of the Kreisau Circle resistance \n\
organization, and three of his men are being held \n\
to the ground  by Wilhelm \"Deathshead\" Strasse, \n\
head of the Nazi SS Special Project Division, \n\
and his Super Soldiers. \n\
\"All you need to do, is look to the one\n\
you'll have me dissect.\" \n\
\c[gold]It cannot end like this\n\
\"Time is running out Blazkowicz\"\n\
\c[gold]The handcuffs they don't feel too sturdy \n\
\c[gold]maybe I can break them \n\
\"Choose! Or I will turn all of you into fine \n\
specimen!\" \n\
\c[gold]Count to four...inhale \n\
\"BLAZKOWICZ!!\" \n\
\c[gold]Count to four...exhale \n\
\n\
\c[gold](Read more in the QCDE Manual!)\n\
"
},


	{	"Gordon Freeman", "Medium", "100", "125", 
"MIT graduate in Theoretical Physics, currently\n\
\"contracted\" by a mysterious individual known as\n\
the Gman, Freeman fights for his own survival.", 
		"Antigravity Discharge", 
"Pushes nearby monsters and projectiles away\n\
from you.",
		"HEV Suit",
"Immune to environmental damage. \n\
Gains armor when picking LG coils. \n\
Reduces cooldown with BFG cells.", 
		"Extraction",
"When near death, Freeman is forcibly extracted\n\
and placed into a random location by his overseer.\n\
This has an unmodifiable internal cooldown of\n\
60 seconds.",
// Lore /////////////////////////////////////
"\"Rise and shine, Mr Freeman. Rise and shine.\" \n\
\n\
\"You might be wondering what happened after \n\
Doctor Vance's unfortunate departure. \n\
Well, let's just say I took the liberty of extracting \n\
you, once again. I apologize for what must seem to \n\
you  like an arbitrary imposition Doctor Freeman. \n\
I will admit I was immensely annoyed by your escape \n\
at the hands of your newly found friends but, \n\
it is not professional to allow one's feelings \n\
to cloud his judgement especially on the work place. \n\
I have thankfully managed to convince my employers \n\
that you still have much potential in you and they \n\
have urged me to bring you back under their \n\
influence.\n\
Most pressing issue have come into play  and \n\
extraordinary times call for an extraordinary man. \n\
After all, I don't think to recall anybody with a \n\
track record as impressive as yours, in all these \n\
years. I am confident you will come to understand \n\
the circumstances as they unfold, and forgive me \n\
for such an abrupt intermission.\"\n\
"
},


	{	"Vor-Matur", "Heavy", "300", "0", 
"Materialized from Azatoth's dreams, an ungodly\n\
entity bent on conquering or destroying worlds,\n\
for either of them will serve as amusement.", 
		"Horror", 
"Casts a projectile that blinds champions and\n\
causes fear on monsters.",
		"Excess Matter",
"Massive health pool, no armor. Less knockback\n\
but smaller Rocket Jump height.\n\
\c[orange]PvE Only:\c[orange] 20% less damage taken.",
		"Corrosive Blood",
"Blood sprayed when taking damage hurts enemies.",
// Lore /////////////////////////////////////
"It came the day, as it had been written in the cursed \n\
pages of the Necronomicon, that one of these \n\
specters endured the torture of its unholy \n\
delivery.\n\
\n\
With a will so strong only a being of pure hate and \n\
insanity could have,, it gave itself a shape. \n\
Its victorious roar was heard everywhere, from the \n\
deepest oceanic pits where Cthulhu slumbers to the \n\
outmost corners of he Dreamlands.  Thus VorMatur, \n\
the Torturer of Souls, was born: angry, spiteful, \n\
mad, yet capable of logical thinking, unlike its \n\
paternal figure. It lives by one commandment only, \n\
to strangle this world between its amorphous claws \n\
and rid the livings of their will to exist. \n\
\n\
Suffering follows in its wake, everything capable \n\
of human-like intellect it captures and tortures \n\
for years. Most of its victims die or turn into \n\
foaming shells, but those who survive are reborn \n\
through the pain, like VorMatur itself. \n\
\n\
Driven insane, deprived of any semblance of \n\
sentience, as if they were cretinous infants they \n\
look up to their torturer for a purpose when all \n\
else has lost its meaning. And VorMatur hears their \n\
pleas, and like a father it welcomes them to its \n\
family, and teaches them there is no greater goal \n\
than to serve it and spread its word throughout \n\
all of creation. \n\
\n\
\c[brite](Read more in the QCDE Manual!)\n\
\n\
"
},


	{	"Eleena", "Light", "125", "25", 
"Mercenary in attitude and profession, agile and\n\
extremely fast, Eleena seeks collecting bounties\n\
on highly wanted subjects.", 
		"Doppelganger", 
"Deploys a copycat on the field as a distraction\n\
or to trade places with.",
		"Acrobatic",
"Holding \c[gold]+jump \c[green]jumps slightly higher.\n\
\c[gold]+Crouch \c[green]in mid-air drops much faster.", 
		"Training Weights",
"When Eleena has no armor, she gains 20% speed.",
// Lore /////////////////////////////////////
"Centuries past, an ancient race of warriors claimed \n\
the planet Ioxia as their home. The three orbiting \n\
moons, Pyxis, Eyre, and Quod are the only remaining \n\
sites where the precious element Mazrium can be \n\
mined.\n\
The Ioxians hoarded the Mazrium and sold small \n\
rations to the neighboring solar systems,\n\
demanding outrageous fees and services in return. \n\
Eventually, after suffering under this extortion,\n\
the native races of the near worlds attempted\n\
an assault on the planet. Thus began the \"Great \n\
Uprising.\" \n\
\n\
Unfortunately, the Armada met with an impenetrable \n\
field of ion energy that encompassed the moons and \n\
Ioxia. Furthermore, the Ioxians had superior \n\
bio-mech weaponry which managed to cripple the  \n\
Armada in the first few sorties of ionic pulses. \n\
\n\
During this assault, something or someone disabled \n\
the forcefield long enough to allow the remains of \n\
the Armada to sweep across the planet's surface \n\
and wreak havoc on the Ioxian strongholds known as \n\
Citadels. Warriors on the planet Treydan claim the \n\
unknown aid came from one of their clan...a trained \n\
spy named Brakk. This claim was never \n\
substantiated.\n\
In the end, only one Citadel remained among the \n\
ruins. \n\
\n\
\c[brite](Read more in the QCDE Manual!)"
},


	{	"Lucienne", "Light", "100", "50", 
"From a now-extinct race of magic-wielding beings,\n\
Lucienne still pursues the one responsible for\n\
the wiping of her kind: VorMatur.", 
		"Cleansing Fire", 
"Cast a fireball that deals 10% damage of max HP\n\
and curse with +20% damage taken for 2 seconds.\n\
Also can heal allies by 20% of max HP.",
		"Immolation",
"When killed, drop a fireball that explodes after\n\
a bit of time, dealing damage in a huge radius.", 
		"Blessing",
"Lucienne's armor overstack does not degenerate\n\
over time. Heavy armors allows her to overstack\n\
up to \c[white]+100AP \c[green]instead of 75.", 
// Lore /////////////////////////////////////
"\c[gold]Holy Diver You've been down too long in the \n\
\c[gold]midnight sea\n\
\"Good morning kind sir, please forgive me if I \n\
happen to bother you...you look like the kind of man \n\
who knows things, may I ask you a question?\" \n\
\"G'morning to you too sunshine, how can I be of \n\
help?\"
\c[gold]Gotta get away, Holy Diver \n\
\"Say...this may sound a bit weird but...did you \n\
happen to see a tall, fiendishly tall...let's say \n\
man...with a lot of metallic prosthesis? Or have you \n\
heard of somebody who has come across such \n\
figure?\" \n\
\"Tall? Metallic prosthesis? Hahahahaha! I'm sorry \n\
honey, doesn't ring a bell. Although allow me to \n\
say...I don't mean to doubt your words, but that \n\
sounds more like something a man might only run into \n\
in his worse nightmares.\" \n\
\c[gold]Something is coming for you, look out! \n\
\"Heh...I guess you could say so. Well, I'm sorry \n\
for taking time away from your day. I'll be on my \n\
way. Good day sir\" \n\
\"Wowowowowowow what's the hurry honey?! Wouldn't \n\
you like to stay here a bit longer? Y'know, the day \n\
has been a bit slow so far, and I wouldn't mind to \n\
spend some quality time with a fine lady such as \n\
you.\" \n\
\c[gold]You can hide in the sun 'till you see the \n\
\c[gold]light, Oh we will pray it's all right \n\
\"I'm sorry, but you're not my type, have a nice day\" \n\
\"Oh yeah? And what is your type?\" \n\
\"The one that doesn't get easily scared\" \n\
\"Hahahahaha, I ain't scared of anything sweetie, not \n\
even God can put fear into my heart!\" \n\
\"Oh is that so? I guess we could find out about\n\
that...look into my eyes\" \n\
\"Which eyes sugar? You have two really nice eyes \n\
down there that have been staring at me since the \n\
 moment you walked in, maybe you should let me take \n\
a better look...at...thooooo\"
\c[gold]Gotta get away, get away\n\
\n\
\c[gold](Read more in the QCDE Manual!)"
},

	{	"Major", "Heavy", "150", "150", 
"Wearing battlescars that ravage her face like\n\
the medals of conflict, a veteran that keeps on\n\
fighting the long-concluded war on stroggos.", 
		"Airstrike", 
"When using ability, pressing \c[gold]+fire \c[green]will drop a\n\
bomb target on the floor. ",
		"Wall climb",
"Holding \c[gold]+jump \c[green]in front of a wall without pressing\n\
any other button, starts a brief wall climb.", 
		"Tall, Lean and Mean",
"Hitbox is slimmer than all the other heavy champs;\n\
She is able to climb higher stair steps.",
// Lore /////////////////////////////////////
"\"WE ARE DYING SUSAN WAYLAND. BUT JUST LIKE ALL OF \n\
THOSE WHO HAVE PERISHED IN CERBERON, YOU SHALL NOT \n\
LEAVE THIS BATTLEFIELD. YOUR BODY WILL, BUT YOUR MIND \n\
WON'T\" \n\
\n\
\c[brite](Read more in the QCDE Manual!)"
},

	{	"Hunter", "Light", "100", "50", 
"Her head gear is made from a sorg skull and\n\
beautiful feathers, regal ornament for the\n\
leader of the Oruk clan.", 
		"Voodoo Guardian", 
"Summon a skull that will attack nearby enemies\n\
and track other champions.",
		"Sixth Sense",
"Enemies under your crosshair, will leave\n\
a track of their position. \c[red](PvP only)", 
		"Spoil of the Hunt",
"Killing enemies will increase Hunter's health,\n\
armor or ammo capacity for current level and/or\n\
current life.",
// Lore /////////////////////////////////////
"They come to this world bearing no name. \n\
In times of harshness there is no space for such \n\
hollow practices. Immediately after delivery, they \n\
are separated from their families.\n\
\n\
Among the Oruk, identity is not a right, it ought \n\
to be earned. It will not be their lineage nor their \n\
parents' merits that will determine who they will be, \n\
it will be the amount of enemy blood they will shed \n\
on the battlefield. \n\
\n\
Most die without ever meeting their parents. That \n\
privileged is only reserved to those who soar above \n\
their feeble peers, to those who have not disgraced \n\
their ancestors with their frailty and foolishness. \n\
\n\
Hunter never bothered to meet her's, even if \n\
she had won that opportunity. She did not raise  \n\
to the top of her clan as a result of their efforts,\n\
their lives had no meaning to her. Such a snub would \n\
be the principle of endless suffering for any other \n\
family, but in the Oruk clans, an arrogant display \n\
of hauteur of this magnitude could only bring but \n\
pride into the spirit of those who had conceived \n\
her.\n\
\n\
\c[brite](Read more in the QCDE Manual!!)"
},

	{	"Serious Sam", "Heavy", "175", "125", 
"An ex-captain of Earth Defense Force, Sam \"Serious\"\n\
Stone is the living legend who saved Earth from\n\
multiple invasions across space and time.", 
		"Serious Minigun", 
"Pulls out his minigun with \c[gold]80 ammo\c[green].\n\
\c[red]Hourglasses don't reduce cooldown\c[green], instead they\n\
increase minigun ammunition when picked.",
		"Seriously Loaded",
"Carries all three starting weapons: Machinegun,\n\
Shotgun and Nailgun.",
		"Complementary Ammo",
"Gets a serious amount of ammo for the current \n\
weapon when picking up Light and Heavy armors.", 

// Lore /////////////////////////////////////
"
\n ''Good morning Sir, I have a shipment for 
\n Mr. Tah-Um, also known as Mental and Chaad Sheen, 
\n is that you? 
\n Great! I only need a signature here, here 
\n aaaand here, thank you very much, have a nice 
\n day and enjoy!''
\n 
\n TO: Tah-Um / Mental / Chaad Sheen
\n FROM: Your biggest follower
\n SUBJECT: PLAY ME
\n 
\n Hello and welcome to our monthly episode of 
\n ''Serious Cooking''! I am your host Sam ''Serious'' 
\n Stone and today I am going to show you how to cook 
\n my delicious, world renowned, Fillet of Zumb'Ul 
\n with Cucurbito Head Puree. 
\n 
\n Let's start with the ingredients first. 
\n For this recipe you will need: 1 Zumb'Ul thighs, 
\n 1 Cucurbito Head, 2 Fiendian Reptiloid Wings, 
\n 1 Gnaar eye, and don't forget 2-3 garlic cloves, 
\n thyme, olive oil, and butter. 
\n They really help bring out the flavor.
\n 
\n \c[brite](Read more in the QCDE Manual!)
"
},


{	"Postal Dude", "Light", "100", "50", 
"Seemingly calm and easy going, the Postal Dude\n\
goes full psycopathic in a moment's notice. Make\n\
sure you don't get in his way to his daily chores\n\
if you're interested in living another day.", 
		"Diseased Cow Head", 
"Throws a severed cow head; anyone close to it\n\
will be contaminated and take damage over time.\n\
This damage ignores the victim's armor.",
		"Cracked Lungs",
"Megahealth gives up to +100hp \c[cyan]overstack\c[green]. After\n\
40sec (90 in pve), any overstack will degenerate \n\
rapidly; if no \c[cyan]OS\c[green] is present, takes 25dmg instead.\n\
This is cancelled by picking another megahealth.",
		"Crouch Jump",
"Holding \c[gold]Crouch \c[green]then pressing \c[gold]Jump \c[green] allows\n\
a higher jump.", 

// Lore /////////////////////////////////////
"
''Hi there! Have you seen this adorable pooch 
\n recently?.. Sir I am sorry if I am bothering you, 
\n but I do not think there's any need to ignore me. 
\n If you could be so kind to answer my question 
\n I'll be immediately on my way...''
\n 
\n But the old cactus keeps his secrets, for he 
\n has none to share.
\n 
\n ''Well... fuck you then! Fuck you and this shit
\n  town! I don't need your help! I'll do everything 
\n  on my own, as always''.
\n 
\n \c[brite](Read more in the QCDE Manual!)
"
},


{	"Painkiller", "Medium", "100", "125", 
"Daniel was promised to be reunited with his dead\n\
wife if he was to kill Lucifer's minions. He was\n\
ultimately betrayed by angels, devils and death.\n\
Now he just wanders all realms seeking revenge.", 
		"Black Tarot", 
"Allows to select with the \c[gold]directional keys\c[green] up\n\
to 3 tarot effects. Picking the same effect\n\
provides a stronger version of it.",
		"Demon Morph",
"Gathering 66 souls morphs Daniel into his Demon\n\
Form. Powerful, but slow. In PvP, player souls\n\
are worth 11.",
		"Painkiller Weapon",
"Replaces the standard \"Gauntlet\" for the\n\
eponymous weapon, which is slightly stronger\n\
and has an \c[gold]Alt Fire\c[green].", 

// Lore ///////////////////////////////////// hel yeh wikipedia
"
\n Daniel Garner, happily married to his wife 
\n Catherine, was about to take her out for a 
\n birthday meal. As they drove towards their 
\n destination at high speed, in the pouring 
\n rain, Daniel took his eyes off the road to 
\n look at his wife. While his attention was 
\n diverted, he ploughed their car into a truck. 
\n Both of them were killed instantly in the crash.
\n 
\n While Catherine managed to make it to Heaven 
\n and live in harmony, Daniel was trapped in 
\n Purgatory. One day, an angel called Samael 
\n told him that in order to receive purification, 
\n he had to kill four of Lucifer's generals in 
\n order to prevent a war between Heaven and Hell. 
\n Lucifer had been secretly organizing a massive 
\n army that could overwhelm Heaven, taking over 
\n Purgatory in the process. With little choice 
\n available to him, Daniel accepted the task. 
\n
\n With the forces of Hell seizing and corrupting 
\n various parts of Purgatory, Daniel went through 
\n different and random phases of history within 
\n Purgatory, from ancient times to the modern era, 
\n including Medieval Europe, Babylon, the Crusades, 
\n the 1800s, and a time slice of modern industry, 
\n until he was chosen by the Vadrigar to partake 
\n in their eternal battles.
"
},

{	"Intruder", "Medium", "150", "75", 
"He searched for treasures, but in Dusk, he found\n\
himself fighting for his life. He found secrets he\n\
could've never imagined, and acquired eldritch\n\
powers he never asked for.", 
		"Wendigo Curse", 
"Turns invisible if not shooting nor taking damage,\n\
leaving trails behind you. \c[yellow]While fully invisible\c[green], take\n\
and deal less damage with weapons, along with a \n\
low-dmg AoE aura.",
		"\"His sparks\"",
"Killing an enemy imbues you with additional speed\n\
for a short period of time. \c[red]Does not apply when\n\
\c[red]using active ability.",
		"Treasure Hunter \c[orange]-PvE-",
"Finding a secret will reward with +50 armor. This\n\
bonus also applies when found by other players.", 

// Lore /////////////////////////////////////
"Something about him"
},


	// ^ insert more classes here
};
//"
int holding = false; // a clientside map-scope variable

#define PAGE_CLASSINFO     0
#define PAGE_IVORYDESC     1
#define PAGE_CURRENTSTATUS 2

// [Ms] if your first reaction when seeing this script is
//      "what the fuck is this shit", congratulations: your
//      ability to discern beautiful code from ugly serves you well.
//
//      "What is this, SBARINFO?" -- Michaelis, official DBTeam SBARINFO guy
script "QCDE_ClassInfo" (int class, int page) net clientside
{
	// My own class? Or some other?
	if(class == 0)
	{
		int tid = 1000;
		if(IsZandronum(true))
			tid = CheckPlayerCamera(PlayerNumber());
		if(CheckActorInventory(tid, "Class_Ranger"		))	class =  1;
		if(CheckActorInventory(tid, "Class_Doomslayer"	))	class =  2;
		if(CheckActorInventory(tid, "Class_Corvus"		))	class =  3;
		if(CheckActorInventory(tid, "Class_Kane"		))	class =  4;
		if(CheckActorInventory(tid, "Class_Caleb"		))	class =  5;
		if(CheckActorInventory(tid, "Class_Menelkir"	))	class =  6;
		if(CheckActorInventory(tid, "Class_Terminator"	))	class =  7;
		if(CheckActorInventory(tid, "Class_Zedek"		))	class =  8;
		if(CheckActorInventory(tid, "Class_Inquisitor"	))	class =  9;
		if(CheckActorInventory(tid, "Class_Bitterman"	))	class = 10;
		if(CheckActorInventory(tid, "Class_Galen"		))	class = 11;
		if(CheckActorInventory(tid, "Class_Nyx"			))	class = 12;
		if(CheckActorInventory(tid, "Class_Sorgaul"		))	class = 13;
		if(CheckActorInventory(tid, "Class_DukeNukem"	))	class = 14;
		if(CheckActorInventory(tid, "Class_Durandal"	))	class = 15;
		if(CheckActorInventory(tid, "Class_Keel"		))	class = 16;
		if(CheckActorInventory(tid, "Class_Sarge"		))	class = 17;
		if(CheckActorInventory(tid, "Class_LoWang"		))	class = 18;
		if(CheckActorInventory(tid, "Class_Grayson"		))	class = 19;
		if(CheckActorInventory(tid, "Class_Eradicator"	))	class = 20;
		if(CheckActorInventory(tid, "Class_Blazkowicz"	))	class = 21;
		if(CheckActorInventory(tid, "Class_Freeman"		))	class = 22;
		if(CheckActorInventory(tid, "Class_VorMatur"	))	class = 23;
		if(CheckActorInventory(tid, "Class_Eleena"		))	class = 24;
		if(CheckActorInventory(tid, "Class_Lucienne"	))	class = 25;
		if(CheckActorInventory(tid, "Class_Major"		))	class = 26;
		if(CheckActorInventory(tid, "Class_Hunter"		))	class = 27;
		if(CheckActorInventory(tid, "Class_Sam"			))	class = 28;
		if(CheckActorInventory(tid, "Class_Postal"		))	class = 29;
		if(CheckActorInventory(tid, "Class_Painkiller"	))	class = 30;
		if(CheckActorInventory(tid, "Class_Intruder"	))	class = 31;
		// ^ insert more classes here
	}
	
	if(class == 0) terminate; // Spectator, or some other class-less entity
	
	if(class < 0 || class > NUMBER_OF_CLASSES)
	{
		log(s:"Trying to show info about class number ", d:class);
	}
	
	// Pages: 0 is normal, 1 is lore, 2 is current status, others are unimplemented
	if(page < 0) terminate;
	if(page > 1) page = 0;
	
	SetHUDSize(1280,960,1); // double resolution frame, 560x480 in file
	SetFont("ClassBck");	HudMessage(s:"A";HUDMSG_FADEOUT,ID_CLASSINFO_BACK,CR_WHITE,640.0,480.0,58.0,3.0);
	SetFont("ClassFrn");	HudMessage(s:"A";HUDMSG_FADEOUT,ID_CLASSINFO_OVER,CR_WHITE,640.0,480.0,2018,0.07);
	
	class--; // indexing classes from one, arrays from zero
	
	int left   = 120.0;
	int top    =  80.0; 
	int right  = 400.0;
	int bottom = 320.0;
	int margin =  20.0;
	int line   =  15.0;
	int imagrin=  64.0 + margin*2;
	int valgrind=110.0 + imagrin;
	int hair   =   2.0;
	int x,y,col= CR_UNTRANSLATED;
	
	
	// sidebar
	SetHUDSize(1280,960,1);
	x =                 347.0;	SetFont(classPix[class][1]);
	y =                 262.0;	HudMessage(s:"A";HUDMSG_FADEINOUT,ID_CLASSINFO_FACE  ,col,x    ,y    ,58.0,0.05,3.0);
	SetHUDSize(640,480,1);
	x = left + margin +  32.0;	SetFont(classPix[class][0]);
	y =bottom- margin -  80.0;	HudMessage(s:"A";HUDMSG_FADEINOUT,ID_CLASSINFO_BODY  ,col,x    ,y    ,58.0,0.45,3.0);
	SetHUDSize(1280,960,1);
	x =                 284.0;	SetFont(classPix[class][2]);
	y =                 565.0;	HudMessage(s:"A";HUDMSG_FADEINOUT,ID_CLASSINFO_ACTIMG,col,x+0.1,y    ,58.0,0.25,3.0);
	
	str fontpvp = "BIGFONT"  ; str colpvp = "\c[brite]";
	str fontpve = "SMALLFONT"; str colpve = "\c[graey]";
	if(IsPVE()) { fontpvp ^= fontpve ^= fontpvp ^= fontpve; colpvp ^= colpve ^= colpvp ^= colpve; } // xor swaps
	
	SetHUDSize(640,480,1);
	x = 174.0; y = (y / 2) >>16<< 16;
	y = y + 55.0;	SetFont(fontpvp); HudMessage(s:colpvp, s:"PVP: ", d:ACS("PVP CD",class)/35;HUDMSG_FADEINOUT,ID_CLASSINFO_PVPCD,col,x,y+0.2,58.0,0.25,3.0);
	y = y +  5.0;	SetFont(fontpve); HudMessage(s:colpve, s:"PVE: ", d:ACS("PVE CD",class)/35;HUDMSG_FADEINOUT,ID_CLASSINFO_PVECD,col,x,y+0.1,58.0,0.25,3.0);
	
	// The text is in 640x480
	SetHUDSize(640,480,1);
	
	switch(page)
	{
	case PAGE_CLASSINFO:
		// titles
		SetFont("BIGFONT");
		x = 320.0;						y = top + margin;
		HudMessage(s:"\c[bludi]", s:classDoc[class][0];HUDMSG_FADEINOUT,ID_CLASSINFO_TITLE,col,x    ,y+0.1,58.0,0.05,3.0);
		x = left + imagrin;				y = top + margin + line + margin + line*2 + margin;
		HudMessage(s:"\c[brite]Type:"           ;HUDMSG_FADEINOUT,ID_CLASSINFO_TYPEK,col,x+0.1,y+0.2,58.0,0.15,3.0);
										y += line + margin;
		HudMessage(s:"\c[brite]Health:"         ;HUDMSG_FADEINOUT,ID_CLASSINFO_HEALK,col,x+0.1,y+0.2,58.0,0.20,3.0);
										y += line + margin;
		HudMessage(s:"\c[brite]Armor:"          ;HUDMSG_FADEINOUT,ID_CLASSINFO_ARMOK,col,x+0.1,y+0.2,58.0,0.25,3.0);
										y += line + margin;
		HudMessage(s:"\c[brite]Active:"         ;HUDMSG_FADEINOUT,ID_CLASSINFO_ACTIK,col,x+0.1,y+0.2,58.0,0.30,3.0);
										y += line * 4 + hair;
		HudMessage(s:"\c[brite]Passive:"        ;HUDMSG_FADEINOUT,ID_CLASSINFO_PASSK,col,x+0.1,y+0.2,58.0,0.35,3.0);
		if(strlen(classDoc[class][9])) // if has second passive
		{
										y += line * 4 + hair;
		HudMessage(s:"\c[brite]Passive:"        ;HUDMSG_FADEINOUT,ID_CLASSINFO_PAS2K,col,x+0.1,y+0.2,58.0,0.35,3.0);
		}
		
		// text
		SetFont("SMALLFONT");
		x = left + imagrin;				y = top + margin + margin;
		HudMessage(s:classDoc[class][4];HUDMSG_FADEINOUT,ID_CLASSINFO_DESC ,col,x+0.1,y+0.1,58.0,0.05,3.0);
		SetFont("BIGFONT");
		x = left + valgrind;			y += line*3 + margin;
		HudMessage(s:classDoc[class][1];HUDMSG_FADEINOUT,ID_CLASSINFO_TYPEV,col,x+0.1,y+0.2,58.0,0.15,3.0);
										y = top + margin + line + margin + line*2 + margin + line + margin;
		HudMessage(s:classDoc[class][2];HUDMSG_FADEINOUT,ID_CLASSINFO_HEALV,col,x+0.1,y+0.2,58.0,0.20,3.0);
										y += line + margin;
		HudMessage(s:classDoc[class][3];HUDMSG_FADEINOUT,ID_CLASSINFO_ARMOV,col,x+0.1,y+0.2,58.0,0.25,3.0);
		x = left + valgrind;			y += line + margin;
		HudMessage(s:classDoc[class][5];HUDMSG_FADEINOUT,ID_CLASSINFO_ACTIV,col,x+0.1,y+0.2,58.0,0.30,3.0);
		SetFont("SMALLFONT");
		x = left + imagrin;				y += hair;
		HudMessage(s:classDoc[class][6];HUDMSG_FADEINOUT,ID_CLASSINFO_ACTID,col,x+0.1,y+0.1,58.0,0.35,3.0);
		SetFont("BIGFONT");
		x = left + valgrind;			y += line * 4;
		HudMessage(s:classDoc[class][7];HUDMSG_FADEINOUT,ID_CLASSINFO_PASSV,col,x+0.1,y+0.2,58.0,0.30,3.0);
		SetFont("SMALLFONT");
		x = left + imagrin;				y += hair;
		HudMessage(s:classDoc[class][8];HUDMSG_FADEINOUT,ID_CLASSINFO_PASSD,col,x+0.1,y+0.1,58.0,0.40,3.0);
		SetFont("BIGFONT");
		x = left + valgrind;			y += line * 4;
		HudMessage(s:classDoc[class][9];HUDMSG_FADEINOUT,ID_CLASSINFO_PAS2V,col,x+0.1,y+0.2,58.0,0.30,3.0);
		SetFont("SMALLFONT");
		x = left + imagrin;				y += hair;
		HudMessage(s:classDoc[class][10];HUDMSG_FADEINOUT,ID_CLASSINFO_PAS2D,col,x+0.1,y+0.1,58.0,0.40,3.0);
		break;
	case PAGE_IVORYDESC:
		// titles
		SetFont("BIGFONT");
		x = 320.0;						y = top / 2 - margin;
		HudMessage(s:"\c[bludi]", s:classDoc[class][0];HUDMSG_FADEINOUT,ID_CLASSINFO_TITLE,col,x    ,y+0.1,58.0,0.05,3.0);
		
		// text
		SetFont("SMALLFONT");
		x = left + imagrin - 4.0;				y += margin + margin;
		HudMessage(s:classDoc[class][11];
				HUDMSG_FADEINOUT, ID_CLASSINFO_DESC, CR_WHITE,
				x+0.1, y+0.1,
				58.0, 0.05, 3.0);
		break;
	case PAGE_CURRENTSTATUS:
		break;
	default:
		PrintBold(s:"QCDE Error: unexpected classinfo page ", d:page, s:", class ", d:class);
		break;
	}
	
	HudMessage(s:"QC:DE v2.7";HUDMSG_FADEINOUT,ID_CLASSINFO_VERS,col,320.0,480.2,10.0,1.00,8.0);
	LocalAmbientSound("QC/UI/InfoScreen",115);
	
	holding = true;
	while(holding)
	{
		delay(1);
		if((GetPlayerInput(ConsolePlayerNumber(), INPUT_BUTTONS) &~ 
			GetPlayerInput(ConsolePlayerNumber(), INPUT_OLDBUTTONS)) == BT_USE)
		{
			ACS("QCDE_ClassInfo_Stop");
			ACS_NamedExecuteAlways("QCDE_ClassInfo", 0, -~class,-~page);
		}
	}
}

script "QCDE_ClassInfo_Stop" (void) net clientside
{
	int i = ID_CLASSINFO_BACK + 1;
	while(i --> ID_CLASSINFO_OVER)
		HudMessage(s:" "; HUDMSG_PLAIN, i, 0, 0,0, 1873);
	holding = false;
}




//=============================================================================
//
//		Low ammo/health alert
//
//=============================================================================

script "QCDE_LowAmmoAlert_CLIENT" (int sound, int text, int noammo) CLIENTSIDE
{
	if(sound) AmbientSound("QC/UI/PlayerSounds/LowAmmoWarning", 127);
	
	if(!text) terminate;
	
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	str message = "\c[bludi]LOW AMMO";
	if(noammo) message = "\c[red]NO AMMO";
	
	HudMessage(s:message;
			HUDMSG_FADEOUT,ID_LOWAMMO_TEXT,CR_UNTRANSLATED, 256.0,70.0, 0,1.0);
}

script "QCDE_LowHealthAlert_CLIENT" (int sound, int text) CLIENTSIDE
{
	if(sound) AmbientSound("QC/UI/PlayerSounds/LowHealthWarning", 127);
	
	if(!text) terminate;
	
	SetHUDSize(512,384,1);
	SetFont("BIGFONT");
	str message = "\c[bludi]LOW HEALTH";
	
	HudMessage(s:message;
			HUDMSG_FADEOUT,ID_LOWHEALTH_TEXT,CR_UNTRANSLATED, 256.0,90.0, 0,0.5);
}





//=============================================================================
//
//		Grayson's shop visuals
//
//=============================================================================

str AmmoIcons[9] = {
		"",		//0  Empty
		"AmmBullt", //1  bullet
		"AmmShell", //2  shell
		"AmmNails", //3  nail
		"AmmBolts", //4  bolt
		"AmmRockt", //5  rocket
		"AmmCoils", //6  coil
		"AmmSlugs", //7  slug
		"AmmBfugs", //8  bfg
		}; 
		
script "QCDE_GraysonText" (int amount, int mode, int ammoicon)
{
	str message = strparam(s:"+", d:amount);
	
	SetHUDSize(1400,1050,1);
	SetFont("QCFNT100");
	HudMessage(s:message;
			HUDMSG_FADEOUT,ID_GRAYSON_PROMPT ,CR_UNTRANSLATED, 1140.2, 850.0, 1.0,1.0);
	
	if(ammoicon)
	{
		SetHUDSize(2800,2100,1);
		SetFont(AmmoIcons[ammoicon]);
		HudMessage(s:"A";
				HUDMSG_FADEOUT,ID_GRAYSON_ICON,CR_UNTRANSLATED, 2370.1, 1706.0, 1.0,1.0);
	}
	
	// armor cost
	SetHUDSize(1400,1050,1);
	SetFont("QCFNT100");
	HudMessage(s:"-25"; // hardcoded. we'll never ever change armor cost. yeah right. hahahaha
			HUDMSG_FADEOUT,ID_GRAYSON_PROMPT2,CR_UNTRANSLATED, 1140.2, 770.0, 1.0,1.0);
	SetFont("ICONSHLD");
	HudMessage(s:"A";
			HUDMSG_FADEOUT,ID_GRAYSON_ICON2,CR_UNTRANSLATED, 1183.1, 765.0, 1.0,1.0);
	
	// ingenious hack: use "minus" sign as rectangular background
	SetHUDSize(150,113,1);
	SetFont("QCFNT100");
	switch(mode)
	{
		case 0: 
			PlaySound (0, "QC/Abilities/Grayson/PreBuy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_ORANGE,138.2,93.0, 0,1.0); 
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_ORANGE,138.2,84.0, 0,1.0); 
			break;
		case 1: 
			PlaySound (0, "QC/Abilities/Grayson/Buy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_GREEN ,138.2,93.0, 0,1.0); 
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_GREEN ,138.2,84.0, 0,1.0); 
			break;
		case -1: 
			PlaySound (0, "QC/Abilities/Grayson/CantBuy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_ORANGE,138.2,93.0, 0,1.0); 
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_RED   ,138.2,84.0, 0,1.0); 
			break;
		case -2: 
			PlaySound (0, "QC/Abilities/Grayson/CantBuy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_RED   ,138.2,93.0, 0,1.0); 
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_GREEN ,138.2,84.0, 0,1.0); 
			break;
	}
}

//=============================================================================
//
//		Eradicator murderface visuals
//		(unused)
//
//=============================================================================



script "QCDE_EradicatorHint" (int percentage, int kills_more)
{
	
	SetHUDSize(1400,1050,1);
	SetFont("BIGFONT");
	
	if(percentage > 0)
	{
		HudMessage(s:"\c[bludi]+", d:percentage, s:"% \c[brite]base damage";
				HUDMSG_FADEOUT,ID_ERADICATOR_PERC,CR_UNTRANSLATED, 1140.2, 968.0, 100.0,200.0);
	}
	
	HudMessage(s:"\c[white]", d:kills_more, s:" kills to buff";
			HUDMSG_FADEOUT,ID_ERADICATOR_MORE,CR_UNTRANSLATED, 1140.2, 988.0, 100.0,200.0);
}





//=============================================================================
//
//		Freeze speedometer
// reuses Starting Weapon ID
//
//=============================================================================



script "QCDE_FreezeIndicator_CLIENT" (int percentage) CLIENTSIDE
{
	if(percentage <= 0) terminate;
	if(percentage > 90) percentage = 90;
	
	int fadein = 0.2 - (percentage * 0.011);
	int stay = -0.2 + (percentage * 0.011);
	int fadeout = percentage * 0.022;
	
	if(fadein < 0) fadein = 0;
	if(stay < 0) stay = 0;
	
	SetHUDSize(1400 - percentage * 2,1050 - percentage * 2,1);
	SetFont("FLAKES01");
	
	HudMessage(s:"A";
			HUDMSG_FADEINOUT,ID_CHANGEWEAPON_OVER + percentage / 10,CR_UNTRANSLATED, 700.0 - percentage * 1.0, 616.0 - percentage * 2.0, stay,fadein,fadeout);
}


//=============================================================================
//
// Titlemap export
//
//=============================================================================

Script "QCDE_ShowVersionNumber" (void)
{
	SetHudSize(960,720,0);
	HudMessageBold(s:"v2.7";HUDMSG_PLAIN,ID_TITLEMAP_VERSION,CR_WHITE, 955.0, 710.0, 0);
}



//=============================================================================
//
// Monster packs load indication
//
//=============================================================================

int currentPack = THEMES_BUILTIN;
Script "QCDE_ShowMonsterPack" (int packname)
{
	int packWas = currentPack++;
	
	SetHudSize(800,600,0);
	SetFont("CONFONT");
	HudMessageBold(s:"\c[brite]Registered custom monsters sets:";HUDMSG_FADEOUT,ID_TITLEMAP_THEMES,          -1, 0.1, 480.0,        0, 20.0);
	
	delay(packWas * 3);
	AmbientSound("menu/dismiss", 127);
	
	int yofs = (packWas - THEMES_BUILTIN) * 10.0;
	if(yofs > 80.0) yofs -= 550.0;
	HudMessageBold(s:"\c[brite]theme", d:packWas, s:": \ck",s:packname;HUDMSG_TYPEON,ID_TITLEMAP_THEMES + packWas,-1, 0.1, 500.0 + yofs, 0, 0.06, 20.0);
}



//=============================================================================
//
//		Weapon Upgrade
//
//=============================================================================

Script "QCDE_UpgradeAcquired" (int weapon, int upgrade)
{
	if(upgrade < 1 || upgrade > 3 || weapon < 0 || weapon >= NUMBER_OF_WEAPONS)
	{
		log(s:"QCDE Error: acquired undefined weapon ", d:weapon, s:" upgrade ", d:upgrade);
		terminate;
	}
	
	// Upgrade indices are 1-based, but array indices are 0-based
	upgrade--;
	
	SetHUDSize(1024,768,1);
	SetFont("UpgrdGot");            HudMessage(s:"A";HUDMSG_FADEINOUT,ID_UPGRADE_BACK,-1, 512.0,472.1, 4.0,0.1,3.0);
	
	// Name
	SetHUDSize(400,300,1);
	SetFont("ESFONTAA");
	str color = strparam(s:"\c[", s:weaponList[weapon], s:"]");
	HudMessage(s:color, s:weaponUpgrades[weapon][upgrade][WU_PROPERNAME], s:" \c[white]", s:weaponUpgrades[weapon][upgrade][WU_SUFFIX]; 
						HUDMSG_FADEINOUT,ID_UPGRADE_TEXT   ,-1, 135.1,200.1, 5.0,0.1,3.0);
	// Description
	SetHUDSize(400,300,1);
	SetFont("ESFONTAA");
	color = "\c[brite]";
	HudMessage(s:color, s:weaponUpgrades[weapon][upgrade][WU_DESC1], s:"\n", s:color, s:weaponUpgrades[weapon][upgrade][WU_DESC2], s:"\n", s:color, s:weaponUpgrades[weapon][upgrade][WU_DESC3]; 
						HUDMSG_FADEINOUT,ID_UPGRADE_DESC   ,-1, 135.1,215.1, 5.0,0.1,3.0);
	
	// Weapon outline
	SetHUDSize(800,600,1);
	if(CheckInventory(weaponList[weapon]))
		 SetFont(weaponUpgrades[weapon][upgrade][WU_WEAPONFULL]);
	else SetFont(weaponUpgrades[weapon][upgrade][WU_WEAPONICON]);
	HudMessage(s:"A"; 	HUDMSG_FADEINOUT,ID_UPGRADE_OUTLINE,-1, 100.0,429.0, 5.0,0.1,2.0);
	// Icon
	SetHUDSize(1600,1200,1);
	SetFont(weaponUpgrades[weapon][upgrade][WU_ICON]);
	HudMessage(s:"A"; 	HUDMSG_FADEINOUT,ID_UPGRADE_ICON   ,-1, 400.0,858.0, 5.0,0.1,2.0);
	
	LogTo(PlayerNumber(), strparam(s:"\c[red]Picked up an upgrade: \c[brite]", s:weaponUpgrades[weapon][upgrade][WU_PROPERNAME], s:" ", s:weaponUpgrades[weapon][upgrade][WU_SUFFIX], s:"\n",
		s:weaponUpgrades[weapon][upgrade][WU_DESC1], s:"\n",
		s:weaponUpgrades[weapon][upgrade][WU_DESC2], s:"\n",
		s:weaponUpgrades[weapon][upgrade][WU_DESC3]));
}



//=============================================================================
//
// Indicate Major ability charges
//
//=============================================================================

#define MAJOR_BOMB_X_GAP 60.0
#define MAJOR_BOMB_Y_GAP 70.0
#define MAJOR_BOMBS_IN_ROW  4
#define MAJOR_START_X     800.0 - (MAJOR_BOMB_X_GAP * 3 / 2)
#define MAJOR_START_Y     800.0
Script "QCDE_MajorCharges" (int charges, int consume)
{
	if(charges <  0) terminate;
	if(charges >  8) charges = 8; 
	if(charges == 8) consume = false;
	
	SetHudSize(1600,1200,0);
	SetFont("ONE_BOMB");
	
	int hmid = HMID_CHARGES;
	int row, col;
	while(charges --> 0)
	{
		HudMessage(s:"A";HUDMSG_PLAIN,hmid,-1, MAJOR_START_X + MAJOR_BOMB_X_GAP * col, MAJOR_START_Y + MAJOR_BOMB_Y_GAP * row, 4.0);
		
		col++;
		if(col >= MAJOR_BOMBS_IN_ROW) { col = 0; row++; }
		
		hmid++;
	}
	
	SetFont("GONEBOMB");
	if(consume)
	{
		HudMessage(s:"A";HUDMSG_FADEOUT,hmid,-1, MAJOR_START_X + MAJOR_BOMB_X_GAP * col, MAJOR_START_Y + MAJOR_BOMB_Y_GAP * row, 0, 0.2);
	}

}




//=============================================================================
//
// Indicate Postal cow gas level
//
//=============================================================================

#define POSTAL_GAS_X_GAP 30.0
#define POSTAL_GAS_MAX   13
#define POSTAL_START_X  900.1
#define POSTAL_START_Y 1100.0
Script "QCDE_CowGasLevel" (int level, int victimtid) clientside
{
	if(level < 0) terminate;
	if(level > POSTAL_GAS_MAX) level = POSTAL_GAS_MAX; 
	if(victimtid != CheckPlayerCamera(CPN())) terminate;
	level *= 2;
	
	SetHudSize(1800,1400,0);
	
	int hmid = HMID_COW_GAS;
	int flags = HUDMSG_FADEOUT|HUDMSG_ADDBLEND|HUDMSG_ALPHA;
	SetActivator(victimtid);
	while(level --> 0)
	{
		str sprite = "POSTPOIS";
		SetFont(sprite);
		HudMessageBold(s:"A";flags,hmid,-1, POSTAL_START_X + ((POSTAL_GAS_X_GAP * (level / 2 * 2 + 1)) * ((level % 2 * 2) - 1)), POSTAL_START_Y, 1.1, 0.5);
		
		hmid++;
	}
}


//=============================================================================
//
//		Class picker
//
//=============================================================================

#define CP_CARDS_ROW 11
#define CP_CARDS_COL  3

int cp_tics; // clientside map variable
script "QCDE_ClassPicker" (int team) net clientside
{
	ConsoleCommand("closemenu");
	
	if(isTeamgame() && !team && PlayerInGame(CPN()))
		team = PlayerTeam() + 1;
	
	// Repeatedly calling menu: need to timeout previous menu
	if(cp_tics > 0)
	{
		cp_tics = 0;
		delay(1);
		if(team) team = 3 - team;
	}
	
	int clid = CheckInventory("ClassID");
	if(!clid) clid = cpcards_serialized[GetUserCvar(CPN(), "playerclass")];
	if(clid == -1) clid = 0;
	int ix = GetIX(clid), iy = GetIY(clid);
	
	
	ACS("QCDE_ClassPicker_Main", team);
	ACS("QCDE_ClassPicker_Desc", clid);
	ACS("QCDE_ClassPicker_Highlight", ix, iy);
	
	int oldbuttons, buttons, triggers, ws_axis, ad_axis;
	cp_tics = CP_STAY_TIME / 1.0 * 35;
	while(cp_tics --> 0)
	{
		int movix = 0, moviy = 0;
		// Player input information
		oldbuttons = buttons;
		buttons = GetPlayerInput(-1, INPUT_BUTTONS);
		ws_axis = GetPlayerInput(-1, INPUT_FORWARDMOVE);
		ad_axis = GetPlayerInput(-1, INPUT_SIDEMOVE);
		if(ws_axis < 0) buttons |= BT_BACK;
		if(ws_axis > 0) buttons |= BT_FORWARD;
		if(ad_axis < 0) buttons |= BT_MOVELEFT;
		if(ad_axis > 0) buttons |= BT_MOVERIGHT;
		triggers = buttons & ~oldbuttons;
		
		if(triggers & BT_BACK     ) moviy += 1;
		if(triggers & BT_FORWARD  ) moviy -= 1;
		if(triggers & BT_MOVEDOWN ) moviy += 1;
		if(triggers & BT_MOVEUP   ) moviy -= 1;
		if(triggers & BT_CROUCH   ) moviy += 1;
		if(triggers & BT_JUMP     ) moviy -= 1;
		
		if(triggers & BT_MOVERIGHT) movix += 1;
		if(triggers & BT_MOVELEFT ) movix -= 1;
		if(triggers & BT_RIGHT    ) movix += 1;
		if(triggers & BT_LEFT     ) movix -= 1;
		
		
		// Update time
		if(movix | moviy)
		{
			// Bounds
			clid = -1;
			while(clid == -1) // iterate over -1's if any are encountered
			{
				ix += movix; iy += moviy;
				
				if(ix >= CP_CARDS_ROW) ix = 0;
				if(ix < 0) ix =~-CP_CARDS_ROW;
				
				if(iy >= CP_CARDS_COL) iy = 0;
				if(iy < 0) iy =~-CP_CARDS_COL;
				
				clid = cpcards[iy][ix];
			}
			
			clid = cpcards[iy][ix];
			ACS("QCDE_ClassPicker_Highlight", ix, iy);
			ACS("QCDE_ClassPicker_Desc", clid);
		}
		
		// Can I have uhhhhhh, can I have uhhhhhhhhhhhhhhhhhhhh, can I uhhhh have uhhhhhhhhhhhhhhhhhhhhhhhhhhhh (*this)
		if(triggers & (BT_ATTACK | BT_USE))
		{
			// Not banned BTW?
			if(!GetCvar(strparam(s:"_bc_", d:clid)))
			{
				ACS("QCDE_ClassPicker_Clear");
				ACS("QCDE_ClassPicker_Highlight", ix, iy, true);
				ACS("QCDE_JoinClassIdx", iy+1, ix, team);
				
				// This is Burger King ma'am, we only serve #15 foot lettuce
				// (Hints about why you can't have uhhhhhhhhhhhhhhhhhhhhhh this->now())
				if(!PlayerIsSpectator(CPN()))
					if(GetActorProperty(0, APROP_Health) > 0)
						ACS("QCDE_ClassPicker_Soon", ix, iy);
			}
			else
			{
				// This switch is currently OFF.
				ACS("QCDE_ClassPicker_Cant", ix, iy);
			}
		}
		
		// Can you don't
		if(triggers & BT_ALTATTACK)
		{
			ACS("QCDE_ClassPicker_Clear");
		}
		
		delay(1);
	}
	//delay(60);
	//ACS("QCDE_ClassPicker_Clear");
}

function int GetIX(int clid)
{
	int ix, iy;
	for(iy = 0; iy < CP_CARDS_COL; iy++)
	for(ix = 0; ix < CP_CARDS_ROW; ix++)
		if(cpcards[iy][ix] == clid) return ix;
		
	log(s:"\c[bludi]QCDE Error: \c- couldn't find ix for ", d:clid, s:" on player ", n:0);
	return 0;
}

function int GetIY(int clid)
{
	int ix, iy;
	for(iy = 0; iy < CP_CARDS_COL; iy++)
	for(ix = 0; ix < CP_CARDS_ROW; ix++)
		if(cpcards[iy][ix] == clid) return iy;
		
	log(s:"\c[bludi]QCDE Error: \c- couldn't find iy for ", d:clid, s:" on player ", n:0);
	return 0;
}

script "QCDE_ClassPicker_Clear" (void) clientside
{
	int hmid =-~ HMID_CP_BACK2;
	while(hmid --> HMID_CP_CARD_FLASH)
		HudMessage(s:"";HUDMSG_PLAIN,hmid,-1, 0,0, 0);
	cp_tics = 0;
}

// Made for virtual 800x600
#define CP_X          0.0
#define CP_Y        100.0
#define CP_TITLE_X  400.0
#define CP_TITLE_Y   80.0
#define CP_BACK_X  -200.0
#define CP_BACK_Y  -100.0
#define CP_CARDS_X   10.0
#define CP_CARDS_Y   40.0
#define CP_TYPE_X    -4.9
#define CP_TYPE_Y     0.0
#define CP_CARD_W    50.0
#define CP_CARD_H   100.0
#define CP_CARD_X     5.0
#define CP_CARD_Y     5.0
#define CP_CARD_PX   15.0
#define CP_CARD_PY   50.0
#define CP_CARD_HLX  15.0
#define CP_CARD_HLY  40.0
#define CP_DESC_X    50.0
#define CP_DESC_Y   -20.0
#define CP_NAME_X    50.0
#define CP_NAME_Y    40.0
#define CP_PORTR_X   50.0
#define CP_PORTR_Y   38.0
#define CP_FIGUR_X   50.0
#define CP_FIGUR_Y  198.0
#define CP_ABICO_X   50.0
#define CP_ABICO_Y  260.0
#define CP_ABIL1_X   50.0
#define CP_ABIL1_Y  300.0
#define CP_ABIL2_X   50.0
#define CP_ABIL2_Y  330.0
#define CP_ABIL3_X   50.0
#define CP_ABIL3_Y  360.0
#define CP_SOON_X    70.1
#define CP_SOON_Y     0.0
#define CP_WHEN_X   400.0
#define CP_WHEN_Y   490.0

#define CP_STAY_TIME 300.0

int cpcards[CP_CARDS_COL][CP_CARDS_ROW] = {
	{ 3,  4,  5, 11, 14, 17, 23, 24, 26, 28, -1, },
	{ 0,  1,  2, 10, 13, 16, 18, 20, 21, 29, 30, },
	{ 6,  7,  8, 12,  9, 15, 19, 22, 25, 27, -1, },
};

int cpcardsxoffset[CP_CARDS_COL] = { 0,-CP_CARD_W / 3 & 0xFFFF0000,0 };

// Convert from playerclass cvar return into canonical ID
int cpcards_serialized[NUMBER_OF_CLASSES] = {
	 0,  1,  2, 10, 13, 16, 18, 20, 21, 29, 30,
	 3,  4,  5, 11, 14, 17, 23, 24, 26, 28,
	 6,  7,  8, 12,  9, 15, 19, 22, 25, 27,
};
// ^ insert more classes here (actually, just file [Ms] a ticket)

script "QCDE_ClassPicker_Main" (int team) clientside
{
	SetHUDSize(600,450,1);
	SetFont("BIGFONT");
	HudMessage(s:"\c[brite]SELECT YOUR CHAMPION";HUDMSG_FADEOUT,HMID_CP_TITLE,-1, CP_TITLE_X * 3/4 >>16<< 16, (CP_TITLE_Y * 3/4 >>16<< 16) ,  CP_STAY_TIME,1.0);
	
	SetHUDSize(2400,1800,1);
	switch(team)
	{
	default:
	case 0: SetFont("CPicker0"); break;
	case 1: SetFont("CPickerB"); break;
	case 2: SetFont("CPickerR"); break;
	}
	HudMessage(s:"A";HUDMSG_FADEOUT,HMID_CP_BACK ,-1, 1200.0,900.0, CP_STAY_TIME,1.0);
	HudMessage(s:"A";HUDMSG_FADEOUT,HMID_CP_BACK2,-1, 1200.0,900.0, CP_STAY_TIME,1.0);
	
	SetHUDSize(800,600,1);
	int ix, iy;
	for(iy = 0; iy < CP_CARDS_COL; iy++)
	for(ix = 0; ix < CP_CARDS_ROW; ix++)
	{
		if(cpcards[iy][ix] < 0) continue;
		SetFont(getcpdata(1,iy+1,ix)); 
		int x = CP_X  +  CP_CARDS_X  +  CP_CARD_PX  +  ix * (CP_CARD_W + CP_CARD_X) + cpcardsxoffset[iy],
		    y = CP_Y  +  CP_CARDS_Y  +  CP_CARD_PY  +  iy * (CP_CARD_H + CP_CARD_Y);
		HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_CP_BACK_CARDS + iy*CP_CARDS_ROW + ix, -1, x,y, CP_STAY_TIME,1.0);
	}
	
	SetFont("BIGFONT");
	HudMessage(s:"\c[graey]LIGHT" ; HUDMSG_FADEOUT, HMID_CP_BODY_TYPE1, -1, CP_X + CP_CARDS_X + CP_TYPE_X + cpcardsxoffset[0], CP_Y + CP_CARDS_Y + CP_TYPE_Y + 0 * (CP_CARD_H + CP_CARD_Y), CP_STAY_TIME, 1.0);
	HudMessage(s:"\c[graey]MEDIUM"; HUDMSG_FADEOUT, HMID_CP_BODY_TYPE2, -1, CP_X + CP_CARDS_X + CP_TYPE_X + cpcardsxoffset[1], CP_Y + CP_CARDS_Y + CP_TYPE_Y + 1 * (CP_CARD_H + CP_CARD_Y), CP_STAY_TIME, 1.0);
	HudMessage(s:"\c[graey]HEAVY" ; HUDMSG_FADEOUT, HMID_CP_BODY_TYPE3, -1, CP_X + CP_CARDS_X + CP_TYPE_X + cpcardsxoffset[2], CP_Y + CP_CARDS_Y + CP_TYPE_Y + 2 * (CP_CARD_H + CP_CARD_Y), CP_STAY_TIME, 1.0);
	
	SetHUDSize(1200,900,1);
	
	str gamety = "";
	if((GameType() == GAME_NET_COOPERATIVE) && (PlayerInGame(PlayerNumber()))) gamety = "New class will be applied during map transition, or after respawn (with inventory loss). Fire to confirm, alt-fire to dismiss.";
	if((GameType() == GAME_NET_DEATHMATCH)  && (PlayerInGame(PlayerNumber()))) gamety = "New class will be applied on respawn. Fire to confirm, alt-fire to dismiss.";
	
	HudMessage(s:"\c[orange]", s:gamety;HUDMSG_FADEOUT,HMID_CP_WHEN,-1, CP_WHEN_X * 3/2 >>16<< 16, CP_WHEN_Y * 3/2 >>16<< 16, CP_STAY_TIME,1.0);
}

script "QCDE_ClassPicker_Highlight" (int ix, int iy, int green) clientside
{
	if(ix < 0 || iy < 0) terminate;
	if(ix >= CP_CARDS_ROW || iy >= CP_CARDS_COL) terminate;
	int time = CP_STAY_TIME;
	if(green) time = 0.5;
	SetHUDSize(800,600,1);
	SetFont(getcpdata(1,iy+1,ix)); 
	int x = CP_X  +  CP_CARDS_X  +  CP_CARD_PX  +  ix * (CP_CARD_W + CP_CARD_X) + cpcardsxoffset[iy],
		y = CP_Y  +  CP_CARDS_Y  +  CP_CARD_PY  +  iy * (CP_CARD_H + CP_CARD_Y);
	HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_CP_CURRENT_CARD, -1, x,y, time,1.0);
	
	x += CP_CARD_HLX - CP_CARD_PX;
	y += CP_CARD_HLY - CP_CARD_PY;
	SetFont("cpicker2"); 
	if(green) SetFont("cpicker1"); 
	HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_CP_CARD_FLASH, -1, x,y,  0.0,0.5);
	HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_CP_CARD_FRAME, -1, x,y, time,1.0);
}

script "QCDE_ClassPicker_Soon" (int ix, int iy) clientside
{
	if(ix < 0 || iy < 0) terminate;
	if(ix >= CP_CARDS_ROW || iy >= CP_CARDS_COL) terminate;
	SetHUDSize(800,600,1);
	SetFont("BIGFONT"); 
	int x = CP_X  +  CP_CARDS_X  +  CP_SOON_X  +  ix * (CP_CARD_W + CP_CARD_X) + cpcardsxoffset[iy],
		y = CP_Y  +  CP_CARDS_Y  +  CP_SOON_Y  +  iy * (CP_CARD_H + CP_CARD_Y);
	str excuse;
	//log(s:"Gametype = ", d:GameType(), s:" == ", d:GAME_SINGLE_PLAYER);
	switch(GameType())
	{
	case GAME_SINGLE_PLAYER: 
		excuse = "chosen for a new game."; break;
	case GAME_NET_COOPERATIVE: 
	case GAME_NET_DEATHMATCH:
	default:
		excuse = "ready for respawn."; break;
	case GAME_TITLE_MAP:
		excuse = "wait. who are you?\n how did you get into my house?"; break;
	}
	HudMessage(s:"\c[brite]", s:classDoc[cpcards[iy][ix]][0], s:"\n\c[white]", s:excuse; HUDMSG_FADEOUT, HMID_CP_DESC_NAME, -1, x,y, 0.0,4.0);
}

script "QCDE_ClassPicker_Cant" (int ix, int iy) clientside
{
	if(ix < 0 || iy < 0) terminate;
	if(ix >= CP_CARDS_ROW || iy >= CP_CARDS_COL) terminate;
	SetHUDSize(800,600,1);
	SetFont("BIGFONT"); 
	int x = CP_X  +  CP_CARDS_X  +  CP_SOON_X  +  ix * (CP_CARD_W + CP_CARD_X) + cpcardsxoffset[iy],
		y = CP_Y  +  CP_CARDS_Y  +  CP_SOON_Y  +  iy * (CP_CARD_H + CP_CARD_Y);
	str apology = "\c[orange]forbidden by\n \c[orange]the server.";
	//log(s:"Gametype = ", d:GameType(), s:" == ", d:GAME_SINGLE_PLAYER);
	
	HudMessage(s:"\c[brite]", s:classDoc[cpcards[iy][ix]][0], s:"\n", s:apology; HUDMSG_FADEOUT, HMID_CP_DESC_NAME, -1, x,y, 0.0,4.0);
	
	int time = CP_STAY_TIME;
	x += CP_CARD_HLX  -  CP_SOON_X;
	y += CP_CARD_HLY  -  CP_SOON_Y;
	
	SetFont("cpicker3"); 
	HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_CP_CARD_FLASH, -1, x,y,  0.5,1.0);
	//HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_CP_CARD_FRAME, -1, x,y,  0.5,1.0);
}

script "QCDE_ClassPicker_Desc" (int which) clientside
{
	int xoffs = CP_X + CP_DESC_X + CP_CARDS_ROW * (CP_CARD_X + CP_CARD_W);
	int yoffs = CP_Y + CP_DESC_Y;
	
	SetHUDSize(800,600,1);
	
	SetFont(classPix[which][0]); 
		HudMessage(s:"A";HUDMSG_FADEOUT,HMID_CP_DESC_FIGURINE,-1, xoffs + CP_FIGUR_X, yoffs + CP_FIGUR_Y, CP_STAY_TIME,1.0);
	
	SetFont("BIGFONT");
	HudMessage(s:"\c[brite]", s:classDoc[which][5];HUDMSG_FADEOUT,HMID_CP_DESC_ABIL1,-1, xoffs + CP_ABIL1_X, yoffs + CP_ABIL1_Y, CP_STAY_TIME,1.0);
	HudMessage(s:"\c[graey]", s:classDoc[which][7];HUDMSG_FADEOUT,HMID_CP_DESC_ABIL2,-1, xoffs + CP_ABIL2_X, yoffs + CP_ABIL2_Y, CP_STAY_TIME,1.0);
	HudMessage(s:"\c[graey]", s:classDoc[which][9];HUDMSG_FADEOUT,HMID_CP_DESC_ABIL3,-1, xoffs + CP_ABIL3_X, yoffs + CP_ABIL3_Y, CP_STAY_TIME,1.0);
	
	SetHUDSize(600,450,1);
	
	HudMessage(s:"\c[brite]", s:classDoc[which][0];HUDMSG_FADEOUT,HMID_CP_DESC_NAME, -1, (xoffs + CP_NAME_X) * 3/4 >>16<< 16, ((yoffs + CP_NAME_Y) * 3/4 >>16<< 16) + 0.1,  CP_STAY_TIME,1.0);
	
	SetHUDSize(1200,900,1);
	
	SetFont(classPix[which][2]); 
		HudMessage(s:"A";HUDMSG_FADEOUT,HMID_CP_DESC_ABILICON,-1, (xoffs + CP_ABICO_X) * 3/2 >>16<< 16, (yoffs + CP_ABICO_Y) * 3/2 >>16<< 16, CP_STAY_TIME,1.0);
	
	SetFont(classPix[which][1]); 
		HudMessage(s:"A";HUDMSG_FADEOUT,HMID_CP_DESC_PORTRAIT,-1, (xoffs + CP_PORTR_X) * 3/2 >>16<< 16,((yoffs + CP_PORTR_Y) * 3/2 >>16<< 16) + 0.1, CP_STAY_TIME,1.0);
}



//=============================================================================
//
//		Vormatur's Horror mask
//
//=============================================================================

Script "QCDE_Darkening_Start" (int duration, int fadein, int fadeout) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	AmbientSound("QC/Abilities/VorMatur/Darkened",1.0);
	SetFont("DARKNESS");
	int id = random(0,63);
	SetHudSize(640,480,true);
	HudMessageBold(s:"A"; HUDMSG_FADEINOUT, HMID_VORMATUR_DARKNESS+id, -1, 
			320.0,240.0, duration, fadein, fadeout);
}

Script "QCDE_Darkening_Stop" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	int id;
	for(id=0; id<64; id++)
		HudMessageBold(s:" "; HUDMSG_PLAIN, HMID_VORMATUR_DARKNESS+id, -1, 
			-400.0,-300.0, 0.0);
}


//=============================================================================
//
//		Painkiller's Black Tarot views
//
//=============================================================================

#define ARROW_XOFFS 125.0
#define TAROT_XOFFS 200.0
#define TAROT_TEXT_YOFFS 35.0

#define ARROW_Y 857.0
#define TAROT_Y 765.0

#define TAROT_PICKS_XOFFS 100.0
#define TAROT_PICKS_Y    1020.0

script "QCDE_Tarot_Hint" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	// Prepare messages (they can be quite wordy)
	str moveleft  = GetKeyBinding("+MoveLeft" );
	str forward   = GetKeyBinding("+Forward"  );
	str moveright = GetKeyBinding("+MoveRight");
	
	SetHUDSize(1440,1080,1);
	SetFont("CARDARRL"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_ARROW_L, -1, 1440.0/2-ARROW_XOFFS,943.0,   0,0.5,0.5);
	SetFont("CARDARRU"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_ARROW_U, -1, 1440.0/2            ,ARROW_Y, 0,0.5,0.5);
	SetFont("CARDARRR"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_ARROW_R, -1, 1440.0/2+ARROW_XOFFS,943.0,   0,0.5,0.5);
	
	SetFont("CARDDEFE"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_CARD_L , -1, 1440.0/2-TAROT_XOFFS,943.0,   1.1,0,0.1);
	SetFont("CARDATTA"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_CARD_U , -1, 1440.0/2            ,TAROT_Y, 1.1,0,0.1);
	SetFont("CARDSPEE"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_CARD_R , -1, 1440.0/2+TAROT_XOFFS,943.0,   1.1,0,0.1);
	
	SetFont("BIGFONT");
	HudMessageBold(s:moveleft;	HUDMSG_FADEOUT,HMID_TAROT_TEXT_L,-1, 1440.0/2-TAROT_XOFFS,TAROT_TEXT_YOFFS+943.0,   1.1,0,0.1);
	HudMessageBold(s:forward;	HUDMSG_FADEOUT,HMID_TAROT_TEXT_U,-1, 1440.0/2            ,TAROT_TEXT_YOFFS+TAROT_Y, 1.1,0,0.1);
	HudMessageBold(s:moveright;	HUDMSG_FADEOUT,HMID_TAROT_TEXT_R,-1, 1440.0/2+TAROT_XOFFS,TAROT_TEXT_YOFFS+943.0,   1.1,0,0.1);
}

script "QCDE_Tarot_Hint_Failure" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	AmbientSound("QC/Abilities/Painkiller/Failure", 127);
}

str tarot_success_sound[4] = { 0,
	"QC/Abilities/Painkiller/Defense",
	"QC/Abilities/Painkiller/Attack",
	"QC/Abilities/Painkiller/Speed",
};

str tarot_card_gfx[4] = { "CARDBLNK",
	"CARHDEFE", 
	"CARHATTA", 
	"CARHSPEE", 
};

script "QCDE_Tarot_Hint_Success" (int which, int level, int pickorder) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	if(which < 1 || which > 3 || level < 1 || level > 3) printbold(n:0, s:" selects bad card ", d:which, s:" level ", d:level);
	
	AmbientSound(tarot_success_sound[which], 67 + 20 * level); 
	
	SetHUDSize(1440,1080,1);
	int i;
	for(i =~- pickorder; i < 3; i++)
	{
		SetFont(tarot_card_gfx[which * (i < pickorder)]);
		HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_1 + i, -1, 1440.0/2 + ((i - 1) * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 10.0, 5.0);
	}
	
	int x,y;
	switch(which)
	{
		case 1: x = 1440.0/2-TAROT_XOFFS; y = 943.0; break;
		case 2: x = 1440.0/2          ; y = TAROT_Y; break;
		case 3: x = 1440.0/2+TAROT_XOFFS; y = 943.0; break;
	}
	for(i = 1; i <= 8; i++)
	{
		SetFont(strparam(s:"CARDGLW", d:i));
		HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_CARDGLW +~- pickorder, -1, x,y, 2.0/35, 0.1);
		delay(1);
	}
	
}

script "QCDE_Tarot_Hint_Apply" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	// nothing yet
}

script "QCDE_Tarot_Hint_End" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	SetHUDSize(1440,1080,1);
	SetFont(tarot_card_gfx[0]);
	HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_1, -1, 1440.0/2 + (-1 * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 0.1, 0.2);
	HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_2, -1, 1440.0/2 + ( 0 * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 0.1, 0.2);
	HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_3, -1, 1440.0/2 + ( 1 * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 0.1, 0.2);
}






//=============================================================================
//
//		Intruder's Morale Boost
//
//=============================================================================

Script "QCDE_IntruderMoraleBoost" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;
	
	//AmbientSound("QC/Abilities/VorMatur/Darkened",1.0); 
	SetHudSize(1024, 768, 1);
	SetFont("BIGFONT");
	HudMessageBold(s:"\c[RG]Morale Boost!"; HUDMSG_FADEOUT,0,-1, 222.0,737.0, 1.0,2.0);
}
